### ISSUE TITLE
Feature Set, Vue CLI and some general question

### ISSUE THREAD

**Issue by atomfrede** [jhipster/jhipster-vuejs#1]
* What features do we want to support? 
* Should we build upon vue-cli and if yes which feature do we select? 
* Do we want to use typescript or not? 
* How to start best? Doing a sample jhipster project without client and build vue(cli) based client on that?

What do you think?

**Comment by sahbi-ktifa** [comment]
I created a sample jhipster project, redoing all components as Angular ones :
- I used Axios as recommended by Vue documentation for http request
- Vuelidate for form validation
- VueI18n for dynamic translation
- VueCookie ans VueX to maintain app state
- Webpack configurations were inherited from vue-cli but can clearly be enhanced
- Finally, I did not used TypeScript but regular JavaScript

I should add my work on a fork to let you review it (of course, it's only a draft at the moment, and should be challenged). I'll do it asap.

**Comment by atomfrede** [comment]
Sounds great. We are using a similar stack except VueX as we have quite small micro frontends so not much state management required. I would also go with plain javascript instead of typescript :+1:

**Comment by gurbirdhillon** [comment]
Here are my thoughts: 

- Vue-Cli is good as it can take care of lot of boiler plate setup.
- VueX is nice to have but don't really essential.
- I would also go with plain javascript instead of typescript (preferred by VueJs community)
- Axios is also my fav for http request.

**Comment by sendilkumarn** [comment]
I like @sahbi-ktifa  setup, it does cover most of our wanted features. 

Vue-CLI is a good option, but based on our experiences / discussions / opinions with Angular CLI and CRA. Let us not take that. 

👍 for `JavaScript` but Vue 3 will have a complete focus on `TypeScript` (so we will surely have a discussion that time whether we want to switch to that) - Just a heads up.

**Comment by deepu105** [comment]
I agree with most of it and let's start with what @sahbi-ktifa has. Let's go with what is most used in the Vue community. I think its good to start with VueX as most of the real-world use cases would end up needing some state management. If Vue CLI is useful let's use it but we also need to ensure that the Vue support closely follows Angular/React as well to avoid defragmentation.

Regarding TS vs JS, though I was not a fan of transpiling type systems, after using TS for almost a year I really like it (when used practically and not being a type nazi) its really helpful in code management/refactoring etc and I guess will help our community which is mainly back-end people. SO if possible I would like to stick to TS as we do the same for Angular and React. And as @sendilkumarn pointed out if Vue 3 is gonna focus on TS then as Hipsters we should start that already :wink:

**Comment by gurbirdhillon** [comment]
Here is quick read/benefits for using vue-cl version 3. 
https://medium.com/the-vue-point/vue-cli-3-0-is-here-c42bebe28fbb

**Comment by deepu105** [comment]
In that case we could use Vue CLI with typescript

**Comment by hdurix** [comment]
I currently work on a Vue.js application integrated with JHipster as well. Here are the technologies we chose:
- Vue CLI (really useful and we didn't notice any limitation until now, webpack can still be configured for extra needs), it could be the good project to try to use a CLI and see what solution is best.
- Typescript (it does work very well with Vue, expect it sometimes needs a few tweaks, especially for unit tests) & TSLint
- Jest for unit tests (coverage is well integrated with Vue CLI, as opposed to mocha + chai solution / however some troubles with cache)
- Cypress for e2e tests (no problem using it, it works like a charm)
- Axios for HTTP requests

**Comment by atomfrede** [comment]
+1 so Vue CLI with typescript, jest and cypress and tslint it is.

**Comment by deepu105** [comment]
For e2e wouldnt it be easier to just use the protractor tests from the react client as I believe it can just work as it is without any major change

**Comment by hdurix** [comment]
I agree with @deepu105, if the couple vue+protractor is working, we should use protractor instead of cypress.

**Comment by atomfrede** [comment]
Let's see how it works. I would suggest lets start and maybe give cypress a try as it is the preferred solution in the vue community, so if it works we don't need to maintain special configuration for protractor (writing tests is imho easiert) and we can rely on the power of the vue community and it might attract more vue developers to contribute (maybe).

**Comment by atomfrede** [comment]
@deepu105 Yes makes totally sense. Maybe just let's get started and not too much thinking about what we use for e2e testing now and decide when we need to. There is much work we need to do before.

**Comment by Gnuk** [comment]
@deepu105 In the Vue.js `#q-and-a` [Discord][vue-chat] channel, you can read it:

> evan Hier à 18:26
> `@George` Vue core will be refactored to use TypeScript. In that process we also plan to improve general type-friendlyness of the APIs.
> ^ that's for v3

[vue-chat]: http://chat.vuejs.org

**Comment by deepu105** [comment]
@Gnuk thanks for the info.

I think we shouldn't overcomplicate stuff. Lets stick to options that are available in JHipster to start with so the stack would be

* VueJS written in Typescript
* Jsx or html for templates 
* Vuex
* Vue Router
* Vue CLI
* Axios
* Vuei18n
* Sass and css options (css can be later and Sass can be default for now)
* Jest
* Protractor if it works without any additional work else we can switch to Cypress
* Tslint , prettier

**Comment by deepu105** [comment]
First lets migrate the default monolith app to Vue so that the default options are supported to begin with. Once thats done we can start implementing additional options. Does everyone agree? If so we can create new tickets and decide who will do what.

**Comment by Gnuk** [comment]
Except I don't know how it's difficult to have both Tslint and prettier (cf this [issue](https://github.com/vuejs/vue-cli/issues/761)), i agree with it.

**Comment by sahbi-ktifa** [comment]
I agree too.
Should I still make my work available as a blueprint even if it's only a start using JavaScript or should we rewrite it from scratch using TypeScript and all the above? If so, I'll wait for tickets 😉

**Comment by deepu105** [comment]
I think your work should be good starting point. We can simply rename file
extensions first and should just work fine

**Comment by sendilkumarn** [comment]
@sahbi-ktifa I too agree that we will start with `js` and then gradually move towards `ts` 
I would say `ver.1` can be in `js` and then change to `ts` later.

**Comment by deepu105** [comment]
@jdubois thats a good idea. I'll create tickets and assign the label for the important parts at the beginning of September. Is that ok?

**Comment by jdubois** [comment]
Yes please do.

**Comment by Gnuk** [comment]
There is a discussion to know how to have official Vue CLI [documentation on integration with backend frameworks](https://github.com/vuejs/vue-cli/issues/1563).

I think we could participate to this discussion to help Vue.js community to help them or propose a standard documentation to have Vue CLI with Spring Boot like we'll do with this feature.

What do you think about it ?

**Comment by jdubois** [comment]
@Gnuk yes, definitely +1
VueJS looks like a much nicer project than Angular (I don't know for React), from what I see they are trying to work with third-party projects, and that's awesome. I'll answer on their thread.

**Comment by deepu105** [comment]
closing as its decided
