### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by pradeepachan** [jhipster/jhipster-vuejs#10]
From the README
jhipster -d --blueprint vuejs
Seems to give error.

Instead: 
jhipster -d --blueprint generator-jhipster-vuejs 
Worked for me. 

If it is an error in the README, please update.

**Comment by deepu105** [comment]
No its not a Readme error, both should work. Need to chek this

**Comment by deepu105** [comment]
Which version of JHipster are you using?  it works fine for me with latest master of this repo and latest JHipster. I cannot reproduce so closing this. If you have more info update me
