### ISSUE TITLE
Development status update

### ISSUE THREAD

**Issue by pradeepachan** [jhipster/jhipster-vuejs#11]
Can the author update on the development status - how (in)complete is the current work? What are some plans, todos, roadmap? 

In case, we happen to choose Vue, I will be happy to contribute to this project.

**Comment by deepu105** [comment]
You can see the plan in open issues and that also shows what needs to be done. 
This issue will also give some ideas https://github.com/jhipster/jhipster-vuejs/issues/1

Will probably create a project board for this later but not now as i'm overwhelmed with work
