### ISSUE TITLE
Selected language with i18n in navbar

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-vuejs#117]
Following https://github.com/jhipster/jhipster-vuejs/issues/95 and https://github.com/jhipster/jhipster-vuejs/pull/115
The language is not selected in navbar.

**Comment by atomfrede** [comment]
Does it have something to do with everything in the `utils` not working as expected? I tried to add the webpack moment plugin and I couldn't make it work as the files are not found and therefore the needles not replaced. 

This is from the current master branch:

```
Unable to find webpack/webpack.dev.js or missing required jhipster-needle. Webpack language task not updated with languages: en,de since block was not found. Check if you have enabled translation support.


Unable to find src/main/webapp//app/config/translation.ts or missing required jhipster-needle. Language pipe not updated with languages: en,de since block was not found. Check if you have enabled translation support.
```

**Comment by pascalgrimaud** [comment]
I don't think it is related.
This ticket is very simple: when you click on language menu, you don't know which language is selected.

**Comment by atomfrede** [comment]
Ah just a simple frontend issue. I will open another one for the other problem.

**Comment by atomfrede** [comment]
Btw. we currently don't store the language in the vuex store (if I got it correctly), we should fix that too.

**Comment by atomfrede** [comment]
@sahbi-ktifa I have a PR nearly ready (at least for the style thing). But I have no experience with vuex, so I need a hint how to handle saving current language in the store. I would like to do it in the `TranslationService`. Is it okay to access the store in a service class? And if so, how to inject it there? Or better provide it like `i18n` as method parameter? 

In addition I would like to  access the current language in the `filters` class (for switching to date-fns) as I need the current locale/language there.

**Comment by sahbi-ktifa** [comment]
I think @pascalgrimaud is actually working on this one. I'm not sure but he may confirm this. About vuex, it could be injected using constructor indeed. Inside your service, you can commit to trigger a mutation and it will then set variables for you in the store.

**Comment by pascalgrimaud** [comment]
Oh, I didn't know you're working on this, @atomfrede 
I'm doing another PR to fix https://github.com/jhipster/jhipster-vuejs/issues/118
Give me a few minutes

**Comment by pascalgrimaud** [comment]
See https://github.com/jhipster/jhipster-vuejs/pull/136
@atomfrede : so I think it can help you, if you want to fix this ticket. In this case, can I assign to you this one?

**Comment by atomfrede** [comment]
Yes you can. Seen your MR already :+1:
