### ISSUE TITLE
Support Sass by default and remove CSS as we are planning to deprecate CSS in the future

### ISSUE THREAD

**Issue by deepu105** [jhipster/jhipster-vuejs#127]
Support Sass by default and remove CSS as we are planning to deprecate CSS in the future

**Comment by sahbi-ktifa** [comment]
I'd like to have a look on this one as I'm not very familiar with Sass right now.

**Comment by sahbi-ktifa** [comment]
@deepu105 when you said "Sass by default", do you mean overriding prompt answers to set useSass to true no matter what ?

**Comment by pascalgrimaud** [comment]
@sahbi-ktifa : @gnuk can help you on this, as he's interested about this subject

**Comment by sahbi-ktifa** [comment]
Bounty claimed https://opencollective.com/generator-jhipster/expenses/6352
