### ISSUE TITLE
Register a new account

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-vuejs#149]
I open this ticket as the URL sent by mail (for new account) seems not working
Not sure, but I need to confirm that.

**Comment by atomfrede** [comment]
@jhipster/developers Anyone working on this already? Otherwise I will do it, as this is crucial for a beta release.

**Comment by pascalgrimaud** [comment]
go ahead @atomfrede
From my side, I think I won't be able to work until next year

**Comment by atomfrede** [comment]
Vacation is well deserved!
