### ISSUE TITLE
Relation with User

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-vuejs#153]
The relation with user is not well handled
I will give more details later or will fix it directly.

**Comment by jdubois** [comment]
@pascalgrimaud this is more general than just for VueJS, it is already badly done at the generator level. I'm pretty sure we could allow relationships to the User entity, even with the JDL (when the "User" entity is used) without much changes.

**Comment by pascalgrimaud** [comment]
Thanks @jdubois but a JDL using User relationship which works with Angular/React should work with VueJS too, and yesterday, I saw it was not the case.
It's my fault as we didn't test User relationship in our CICD here.

That's the reason for this ticket.

**Comment by ivangsa** [comment]
@pascalgrimaud this may be fixed by this #155 
I had relations with User in my jdl and that was the only error I found in the generated client
In the server side, relations to User are removed so they have to be fixed manually..

**Comment by pascalgrimaud** [comment]
thanks @ivangsa !
Yes, I need to test your patch

**Comment by pascalgrimaud** [comment]
After testing some PR, and testing some JDL, I don't see issue any more, so let's close this
