### ISSUE TITLE
Vue Components data initialization presents errors when entity has relations

### ISSUE THREAD

**Issue by ivangsa** [jhipster/jhipster-vuejs#155]
Hi
I've been following this blueprint for a while and using it for an [aplication](https://github.com/ivangsa/ecolar/) so I would like to give a hand...

I found that generated 'constructor' for vue Components  has some errors initializing class fields when entity has relations

I belive these fields can be initialized 'inline' to null, {} or [] and still be reactive, so this code would be unnecessary and hard to maintain...

I have already a patch for this https://github.com/ivangsa/jhipster-vuejs/commit/2c58becf57302453bc2bac7f3309f3b18b8a4aaa, I will send a PR soon, after I launch all tests to verify it is all good..

Regards
ivan

**Comment by sahbi-ktifa** [comment]
Great!! Thanks @ivangsa, can't wait for your PR.

**Comment by hdurix** [comment]
That's the way `vue-class-component` is [doing](https://github.com/vuejs/vue-class-component/blob/master/example/src/components/Hello.vue) so yes why not, especially if that prevents from initialization bugs.

But I think we should be consistent, if we change for entity, we should do the same for every component :)

**Comment by ivangsa** [comment]
hi @Gnuk I meant that field nested properties initialization is unnecessary  (i.e. "user = { name: null }") to be reactive..

I learned the hard way that validated properties needs to either be initialized or use the type constructor
myEntity: IMyEntity = {}; // does not work if myEntity has validation
myEntity: IMyEntity = new MyEntity(); // it's reactive and validation works

**Comment by Gnuk** [comment]
Interesting to know. Is there something on Vue listening the constructor ? And about your example from initialization I see another problem because `{}` will implements an interface like IMyEntity only if this interface have no mandatory field.
