### ISSUE TITLE
User creation page

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-vuejs#178]
In user creation page, there is some strange behavior:
- validation fields
- language selection empty

It doesn't work well. 

**Edit:** update -> creation

**Comment by hdurix** [comment]
There is a problem with email validation : `user@localhost` is not valid from the `vuelidate`'s perspective, but `user@localhost.com` is valid. It has been discussed [there](https://github.com/jhipster/generator-jhipster/issues/8367#issuecomment-422936783) and [there](https://github.com/jhipster/generator-jhipster/issues/5810#issuecomment-303201305).

Maybe we should change the default the default email adresses for our users after all...

**Comment by pascalgrimaud** [comment]
Wrong use case, it is creation, not update.
See my screenshot:
![capture d ecran de 2018-12-28 07-17-45](https://user-images.githubusercontent.com/9156882/50504891-ed939d80-0a70-11e9-9638-ef80d7f0a65e.png)
