### ISSUE TITLE
Delete user or entity: error in browser console

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-vuejs#180]
After deleting an entity or user, there are errors in console:

```
Erreur d’analyse XML : aucun élément trouvé
Emplacement : http://localhost:9000/api/totos/31
Numéro de ligne 1, Colonne 1 :
```

**Comment by atomfrede** [comment]
You are also using FF, right? No issue in chromium.  It seems like a FF issue, interpreting an empty response as xml and trying to parse that (which of course doesn't work).

**Comment by atomfrede** [comment]
Yes I would say so. Returning nothing in a response it makes sense to return no-content instead of ok

**Comment by sahbi-ktifa** [comment]
This will be closed when main generator will be fixed using mentionned PR.
