### ISSUE TITLE
Metrics page with Micrometer

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-vuejs#200]
With the hard work by @clement26695, Micrometer is now official in generator-jhipster, after some merges:
- https://github.com/jhipster/generator-jhipster/pull/8812
- https://github.com/jhipster/jhipster/pull/123
- https://github.com/jhipster/ng-jhipster/pull/81
- https://github.com/jhipster/react-jhipster/pull/20

So, the metrics page for Vue.js need to be updated.

**Comment by clement26695** [comment]
I can work on that. It should not be too hard, I just need to become a bit more familiar with vue

**Comment by sahbi-ktifa** [comment]
That would be awesome! Do not hesitate to ping us if you need to!

**Comment by pascalgrimaud** [comment]
Thanks @clement26695 ! I'm pretty sure you'll love Vue.js ;)
