### ISSUE TITLE
Entity 'Instant' will generate a JS 'Moment'

### ISSUE THREAD

**Issue by wdick** [jhipster/jhipster-vuejs#201]
##### **Overview of the issue**

Hi, if you have an entity definition (in a JDL file) like:
```
entity MyEntity {
   name string
   createdAt Instant
}
```

The vuejs generator will generate an entity model using 'Moment' instead of 'Date':
<ws>/shared/model/myentity.model.ts:
```
export interface IMyEntity {
  id?: number;
  name?: string;
  createdAt?: Moment;
}
```

I assume, it should be of type 'Date'.

##### **JHipster Version(s)**

JHipster version 5.7.2
JHipster jhipster-vuejs: current master (07. Jan. 2019)

**Comment by atomfrede** [comment]
You need the current master of the main generator. See https://github.com/jhipster/generator-jhipster/commit/17efde1a21618b0a04bc4fb28d77eb8d8be7cd83
