### ISSUE TITLE
Multiple call to management/info endpoint

### ISSUE THREAD

**Issue by sahbi-ktifa** [jhipster/jhipster-vuejs#210]
##### **Overview of the issue**

On load, two components (ribbon & Navbar) both call to management/info endpoint. We should refactor this behavior to make only one API call and retrieve through through store for example.

##### **Motivation for or Use Case**

Prevent these two uneeded calls.

##### **Reproduce the error**

Just open your app and check your network panel.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by richard-francois** [comment]
Hello, i am working on it. I should update soon

**Comment by richard-francois** [comment]
I managed to make just one call to management/info on init, and store the response into the store defined in config.ts.ejs. Now, i must rewrite ribbon.component.spec.ts.ejs

**Comment by pascalgrimaud** [comment]
Nice @richard-francois !
Don't hesitate to ping us if you need help

**Comment by richard-francois** [comment]
Hello Guys !
At least it seems to work, IT OK. Thanks a lot to @sahbi-ktifa .
It may be perfectible, but as it seems to work, i do the PR.
CU

**Comment by richard-francois** [comment]
Next time, can you assign me an issue please ? like that i will be able to see my pictogram near the ticket ! It's very important ;-)
