### ISSUE TITLE
Maven wrapper build rebuilds front end all the time

### ISSUE THREAD

**Issue by sahbi-ktifa** [jhipster/jhipster-vuejs#218]
##### **Overview of the issue**

Maven wrapper build rebuilds front end all the time even if the front end has already been built.

##### **Motivation for or Use Case**

Gain building time after front has already been built.

##### **Reproduce the error**

Build front-end and try to use './mvnw'. Front should not build again.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by sahbi-ktifa** [comment]
This should help when using hot reload while typing ```./mvnw compile``` after modifications.

**Comment by pascalgrimaud** [comment]
Fixed by https://github.com/jhipster/generator-jhipster/pull/9055
