### ISSUE TITLE
Clean npm test logs output

### ISSUE THREAD

**Issue by sahbi-ktifa** [jhipster/jhipster-vuejs#220]
##### **Overview of the issue**

Currently, ```npm test```outputs some error regarding unhandled promise rejection.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
I think it is because, in entity tests, we didn't inject the other service, when there is a relationship.
We should handle that

**Comment by hdurix** [comment]
We don't have those logs in master anymore, thanks to #231 #243 #254 #262 #312.

But we regularly have new errors of this type, when new code is added. We need to check this when contributing, but these errors can be difficult to catch as they appear only as warnings in logs.

2 solutions I see for fixing that in a long term:
- find how to configure Jest (and node) to fail when a promise is unresolved
- create a little hack in Travis to fail when an error is detected, for instance check if the result of `npm run test 2>&1 >/dev/null | grep "(node:" | wc -l` is `0`.

**Comment by sahbi-ktifa** [comment]
@pascalgrimaud any advice on this one?

**Comment by pascalgrimaud** [comment]
I don't like the hack with Travis, because it will be different with the user. 
I'd prefer to have "find how to configure Jest (and node) to fail when a promise is unresolved"

Let's close this ticket for now as it is solved. 
We can improve the result later

**Comment by sahbi-ktifa** [comment]
I reopen this one as there is clearly still some warnings during CI 
<img width="1548" alt="capture d ecran 2019-02-28 a 08 55 49" src="https://user-images.githubusercontent.com/7074827/53550355-ca4fa200-3b36-11e9-96e2-7d8f95aaf1cd.png">

**Comment by hdurix** [comment]
The failures from your screenshot will be fixed by https://github.com/jhipster/jhipster-vuejs/pull/397/commits/e4ea4278fa4d7fc208337ac0f6b15d4fca72b972.

But I'm still in favor of adding the little hack inside the CI to prevent this :) I've noticed there is still one `UnhandledPromiseRejectionWarning` on something else but I don't have time to investigate right now.

**Comment by pascalgrimaud** [comment]
After thinking about it, I changed my mind about this little hack.
So let's do it

**Comment by qmonmert** [comment]
@sahbi-ktifa & @hdurix PR https://github.com/jhipster/generator-jhipster/pull/12195 to fix all the warning logs
