### ISSUE TITLE
Discussion: compatibility with generator-jhipster

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-vuejs#244]
I think we should use a fixed version of generator-jhipster to be sure it is compatible:
https://github.com/jhipster/jhipster-vuejs/blob/master/package.json#L28

If we keep like this, a major change in generator-jhipster can broke this blueprint.

What do you think ?

**Comment by sahbi-ktifa** [comment]
Yes, I agree, we should only use fixed version.

**Comment by pascalgrimaud** [comment]
What is nice is: all new PR will test with the master version of generator-jhipster, so we'll be aware when something is broken
For release, let's use a fixed version
