### ISSUE TITLE
[minor] generated banner with new colors

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-vuejs#251]
When generating a Vue.js project, the banner is by default the same for Angular (green + red).
I don't know if it is possible to override this, and use our own banner.txt as it comes from server folder.

Some solutions:
- create a new subgenerator server, but it will be overkilled !
- update the generator-jhipster to include this new banner
- another solution ? something like post-hook ?

**Comment by deepu105** [comment]
you can also override the banner directly from the client sub gen as well
by providing the correct paths I guess, it doesn't have to be from server
sub gen, or you can use the common subgen as well

Thanks & Regards,
Deepu

**Comment by pascalgrimaud** [comment]
So, using the common subgen would be the best solution I think.
Let's try this. @sahbi-ktifa is already having a look on this
