### ISSUE TITLE
Add global logout for OIDC authentication

### ISSUE THREAD

**Issue by mraible** [jhipster/jhipster-vuejs#256]
##### **Overview of the feature request**

Global logout was [recently added](https://github.com/jhipster/generator-jhipster/pull/8757) to the main JHipster project. 

##### **Motivation for or Use Case**

It'd be good for the Vue blueprint to have the same features as the main generator.

##### **Related issues or PR**

https://github.com/jhipster/generator-jhipster/pull/8757

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by sahbi-ktifa** [comment]
I'll take care of this as it will properly finish oauth2 support. Thanks @mraible for this notification.

**Comment by mraible** [comment]
@pascalgrimaud Yes, I'd be happy too!
