### ISSUE TITLE
The attribute "v-bind:value" is being removed with no i18n

### ISSUE THREAD

**Issue by Falydoor** [jhipster/jhipster-vuejs#265]
##### **Overview of the issue**

The attribute `v-bind:value` is being removed when generating an app with no i18n.

##### **Motivation for or Use Case**

I think the attribute `v-bind:value` is required no matter if the application use or use not i18n

##### **Reproduce the error**

Simply generate the entities from the jdl

##### **Suggest a Fix**

The regexp `/(v-text=".*?")|(v-bind:placeholder=".*?")|(v-html=".*?")|(v-bind:title=".*?")|(v-bind:label=".*?")|(v-bind:value=".*?")|(v-bind:html=".*?")/g` should include `(v-bind:value="\$t.*?")` in `generators/utils.js`.

That way, only the attribute `v-bind:value` that calls `$t()` will be removed.

##### **JHipster Version(s)**

v5.8.1

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "5.8.1",
    "applicationType": "monolith",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [
      {
        "name": "generator-jhipster-vuejs",
        "version": "1.0.0-beta.0"
      }
    ],
    "enableTranslation": false,
    "clientPackageManager": "npm",
    "blueprint": "generator-jhipster-vuejs",
    "blueprintVersion": "1.0.0-beta.0"
  },
  "generator-jhipster-vuejs": {
    "jhipsterVersion": "5.8.1",
    "applicationType": "monolith",
    "baseName": "jhipster",
    "clientFramework": "vue",
    "useSass": true,
    "clientPackageManager": "npm",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity BankAccount {
  name String required,
  balance BigDecimal required
}
entity Label {
  label String required minlength(3)
}
entity Operation {
  date DateTime required,
  description String,
  amount BigDecimal required
}
relationship OneToMany {
  BankAccount{operation} to Operation{bankAccount(name)}
}
relationship ManyToOne {
  BankAccount{user(login)} to User
}
relationship ManyToMany {
  Operation{label(label)} to Label{operation}
}

paginate Operation with infinite-scroll

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

git version 2.20.1

node: v11.8.0

npm: 6.5.0

Docker version 18.06.1-ce, build e68fc7a

docker-compose version 1.22.0, build f46880f

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by hdurix** [comment]
Is it closed by #266?

**Comment by sahbi-ktifa** [comment]
Nope, I think we need to update cleaning regexp when noi18n is selected. Here is the line involved : https://github.com/jhipster/jhipster-vuejs/blob/319a62039ddfd623a7ee7951b82e55d7cc9047ab/generators/utils.js#L106
