### ISSUE TITLE
Any plan to add nuxt.js as an option?

### ISSUE THREAD

**Issue by TonyLuo** [jhipster/jhipster-vuejs#292]
##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Can you argue why Nuxt.js should be as an option ?
Can you give more details on how it could be done ?

**Comment by jdubois** [comment]
I'd be happy to work with the Nuxt.js guys, they are French and we should meet sometime. 

But I think your question is if the current team is going to do this: there's no plan on anything, it's OSS, things are done when people have time and will to do stuff.

**Comment by atomfrede** [comment]
We won't do it anytime soon, so I suggest to close this.
