### ISSUE TITLE
Enable HTML5 mode

### ISSUE THREAD

**Issue by sahbi-ktifa** [jhipster/jhipster-vuejs#297]
Waiting for this https://github.com/jhipster/generator-jhipster/pull/9098 to get merged before doing it.

It only needs configuration with VueRouter (https://router.vuejs.org/guide/essentials/history-mode.html)

**Comment by pascalgrimaud** [comment]
Just to not forget. We need to take care about :
- this issue: https://github.com/jhipster/generator-jhipster/pull/9593
- this fix by @ruddell : https://github.com/jhipster/generator-jhipster/pull/9593
