### ISSUE TITLE
Release v1.0.0.beta.1 / v0.0.5

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-vuejs#309]
With @sahbi-ktifa, we plan to do another release probably tomorrow (or monday), as @Falydoor will need this, for his full-day workshop on Vue.js with JHipster.

@sahbi-ktifa has the permission on NPM repo now to do it.

@deepu105 : I know how to publish a specific version but not a beta version. Plz, can you provide us what you did for the last release, as you publish 2 versions:
- v0.0.4
- v1.0.0.beta.0

So @sahbi-ktifa can do the same.

**Comment by deepu105** [comment]
That's easy run the below, the `* v0.0.4` was published by accident so ignore that
```
npm version npm version 1.0.0-beta.1
git push --tags
npm publish --tag beta
```

**Comment by pascalgrimaud** [comment]
thanks a lot @deepu105 ! :-)

**Comment by sahbi-ktifa** [comment]
Release 1.0.0-beta.1 done today. Thanks @pascalgrimaud @deepu105

**Comment by pascalgrimaud** [comment]
@Falydoor : can you test and confirm it works well for your workshop ? If needed, we probably can do a new release. Just ask !

**Comment by Falydoor** [comment]
Thanks for the release!

The only issue I have right now is that after installing the blueprint globally by running `npm install -g generator-jhipster-vuejs@1.0.0-beta.1`, I have the below error:

![image](https://user-images.githubusercontent.com/2212267/52974244-df863d00-338e-11e9-8e12-576337f9ce6e.png)

It works if I install the blueprint locally with `npm install generator-jhipster-vuejs@1.0.0-beta.1`.

It's not a big issue but I would like to know if you're able to use the blueprint using the global package.

**Comment by pascalgrimaud** [comment]
yes, only if I install globally both:
- generator-jhipster
- generator-jhipster-vuejs

If one of them uses npm link, I need to use npm link generator-jhipster-vuejs

**Comment by Falydoor** [comment]
I had to run `brew unlink jhipster` because it was overriding the global generator-jhipster.
Thanks!
