### ISSUE TITLE
Provide a new cli command to create a new component page

### ISSUE THREAD

**Issue by sahbi-ktifa** [jhipster/jhipster-vuejs#327]
##### **Overview of the feature request**

Provide directly from cli the ability to create a new page, featuring:
* custom routes
* vue component (SFC file + service)
* vue component unit tests
* protractor tests if enabled

##### **Motivation for or Use Case**

It will provide an easy way for the user to start from scracth a new page 

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by sahbi-ktifa** [comment]
@nonomoho as we discussed it, when this PR https://github.com/jhipster/generator-jhipster/pull/9574 is merged, you should be able to add this feature.

**Comment by nonomoho** [comment]
Hello @sahbi-ktifa,

I worked a little on this issue. I based myself on your work: https://github.com/jhipster/generator-jhipster-blueprint/pull/32.
So I create `cli/commands.js` and `generators/foo/index.js` files to test it but I still get the same error: 
``` bash
INFO! No custom command found within blueprint: generator-jhipster-vuejs
INFO! Using JHipster version installed globally
ERROR! foo is not a known command. See 'jhipster --help'.
```

Can you help me?

**Comment by sahbi-ktifa** [comment]
You have to do npm link in the blueprint but within the main generator as well.

**Comment by pascalgrimaud** [comment]
I think it's a very interesting feature.
In fact, I need this on my current project, so I'm putting a bounty on this, as it is a little bit complex and there are a lot of work before achieving this.
