### ISSUE TITLE
Remove bootswatch questions as now main generator has it

### ISSUE THREAD

**Issue by sahbi-ktifa** [jhipster/jhipster-vuejs#337]
These questions are now handled by the main generator latest version.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
The question is handled by the sub generator client.
And as we override this sub generator, is it possible ?

**Comment by sahbi-ktifa** [comment]
Yes :) we will make it possible if this is not already it
