### ISSUE TITLE
CI with Azure

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-vuejs#342]
I'd suggest to use CI with Azure too. It seems to be more stable for Protractor and maybe help to resolve https://github.com/jhipster/jhipster-vuejs/issues/285

As the Lead of Vue.js, what do you think @sahbi-ktifa ?
Are you ok with that ? If yes, I can start the work.

**Comment by sahbi-ktifa** [comment]
Sure! That would be great!

**Comment by pascalgrimaud** [comment]
ok, self assigned
