### ISSUE TITLE
TypeScript Syntax problem in vue template: "invalid expression: Unexpected token ." e.g. for "editForm.controls.customer?.dirty"

### ISSUE THREAD

**Issue by mhoennig** [jhipster/jhipster-vuejs#345]
##### **Overview of the issue**

After importing my JDL containing two entities with a OneToMany relationship and building the project, I am getting:

`Errors compiling template:

  invalid expression: Unexpected token . in

    !(editForm.controls.customer?.dirty && editForm.controls.customer?.invalid)`

It compiles if I remove the '?' characters, of cause if the variable is null, it leads to an exception at runtime.

##### **Motivation for or Use Case**

Looks like the VueJS blueprints and the configuration don't fit together. 

##### **Reproduce the error**

- created a fresh project with `jhipster --blueprint vuejs`
- import a rather simple JDL file (see below)
- run gradlew

The JDL-File:
```
filter all
dto all with mapstruct
service all with serviceClass
paginate all with  infinite-scroll

entity Customer {
    number Integer required unique min(10000) max(99999),
    prefix String required unique pattern(/[a-z][a-z0-9]+/),
    name String required maxlength(80),
    contractualAddress String required maxlength(400),
    contractualSalutation String maxlength(80),
    billingAddress String maxlength(400),
    billingSalutation String maxlength(80)
}

entity Membership {
    sinceDate LocalDate required,
    untilDate LocalDate
}

relationship OneToMany {
  Customer to Membership{customer(prefix) required},
}

```

##### **Suggest a Fix**

The simplest would be to use ES5 in the templates and TypeScript/ES6 just for the class file. But maybe somebody with better knowledge in VueJS-Single-File-Components and TypeScript configurations has a better solution.

##### **JHipster Version(s)**

v5.8.2, not tried with earlier versions

##### **JHipster configuration**

```
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
##### **JHipster Version(s)**

```
vuetest-0@0.0.0 /home/mi/Projekte/vuetest0
└─┬ generator-jhipster-vuejs@1.0.0-beta2
  └── generator-jhipster@5.8.2 

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "de.javagil.vuetest0"
    },
    "jhipsterVersion": "5.8.2",
    "applicationType": "monolith",
    "baseName": "vuetest0",
    "packageName": "de.javagil.vuetest0",
    "packageFolder": "de/javagil/vuetest0",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "...",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [
      {
        "name": "generator-jhipster-vuejs",
        "version": "1.0.0-beta2"
      }
    ],
    "enableTranslation": false,
    "clientPackageManager": "npm",
    "blueprint": "generator-jhipster-vuejs",
    "blueprintVersion": "1.0.0-beta2",
    "enableHibernateCache": false
  },
  "generator-jhipster-vuejs": {
    "clientTheme": "none",
    "clientThemeVariant": "",
    "jhipsterVersion": "5.8.2",
    "applicationType": "monolith",
    "baseName": "vuetest0",
    "clientFramework": "vue",
    "useSass": true,
    "clientPackageManager": "npm",
    "enableTranslation": false
  }
}
</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Customer {
  number Integer required unique min(10000) max(99999),
  prefix String required unique pattern(/[a-z][a-z0-9]+/),
  name String required maxlength(80),
  contractualAddress String required maxlength(400),
  contractualSalutation String maxlength(80),
  billingAddress String maxlength(400),
  billingSalutation String maxlength(80)
}
entity Membership {
  sinceDate LocalDate required,
  untilDate LocalDate
}
relationship OneToMany {
  Customer{membership} to Membership{customer(prefix) required}
}

dto Customer, Membership with mapstruct
paginate Customer, Membership with infinite-scroll
service Customer, Membership with serviceClass
filter Customer, Membership

</pre>
</details>


##### **Environment and Tools**

java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)

git version 2.17.1

node: v10.15.3

npm: 6.4.1

yeoman: 2.0.5

yarn: 1.3.2

Docker version 18.09.2, build 6247962

INFO! Congratulations, JHipster execution is complete!
```

##### **Browsers and Operating System**

Ubuntu Linux 18.04 - compile problem, not related to any browser

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by sahbi-ktifa** [comment]
Thank you for replying this, I'll look into it asap.

**Comment by mhoennig** [comment]
My guess is, there might be more bugs hidden behind this one.

I've turned the "a?.b" into "a && a.b" and still these expressions, e.g. `<div :hidden="!(editForm.controls.customer` don't work because 'editForm' is undefined. This part seems only to be rendered in the *-update.vue files for entities on the right side of `relationship OneToMany`, thus these components are broken.

**Comment by mhoennig** [comment]
I was puzzled all the time where this editForm is supposed to come from. It looks like this generated code is identical to the Angular frontend, thus trying to use ngForm features with VueJS, right?

**Comment by sahbi-ktifa** [comment]
You seems to be right about that, it should not be used here at all. We still have work to do ;)

I should be able to look into it this week. I'll let you know. Thanks for your feedback though!

**Comment by sahbi-ktifa** [comment]
@mhoennig we were having issues with relationships validation. The PR above fix this!
Thanks for your valuable report!

**Comment by alvarorodriguezestruch** [comment]
I am still having this issue on versión 1.0.0-beta2... Any suggestion?? :)

**Comment by sahbi-ktifa** [comment]
Hello, yes this is normal, we merged the fix in the current master branch, thus 1.0.0-beta2 do not benefits from it.
We're expecting to release final 6.0.0 soon, I'd release vue.js blueprint 1.0.0 just after that.

To fix your problem, switch to the master branch if you can or wait for a few days with the first 1.0.0 release.

Hope that helps.

**Comment by alvarorodriguezestruch** [comment]
Yep, I thought so. I will wait until you release new version. Thanks for the fast response and for all your work and sorry for posting on a  closed thread... :)

**Comment by sahbi-ktifa** [comment]
No problem :)
