### ISSUE TITLE
Use Spring Boot loggers actuator endpoint

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-vuejs#352]
Following this PR by @cbornet : https://github.com/jhipster/generator-jhipster/pull/9620

We need to do the same here.

**Comment by pascalgrimaud** [comment]
@sahbi-ktifa : don't forget this ticket, before the release. Otherwise, the metrics page will be broken
I'll try to fix this ticket, this weekend, if I have time

**Comment by sahbi-ktifa** [comment]
Ok! Let me know, I'll work on this otherwise!
