### ISSUE TITLE
Install doesn't work + updates for JHipster 6 and OIDC

### ISSUE THREAD

**Issue by mraible** [jhipster/jhipster-vuejs#355]
##### **Overview of the issue**

I tried the instructions in the README:

```
npm install -g generator-jhipster-vuejs@1.0.0-beta.2
```

This results in:

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for generator-jhipster-vuejs@1.0.0-beta.2
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mraible/.npm/_logs/2019-04-30T01_46_16_408Z-debug.log
```

##### **Motivation for or Use Case**

I was hoping to update the URL for OIDC from `/login` to `oauth2/authorization/oidc` so this blueprint is compatible with JHipster 6. This change already exists for Angular and React:

* Angular [`login.service.ts`](https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/angular/src/main/webapp/app/core/login/login.service.ts.ejs#L55)
* React [`url-utils.ts`](https://github.com/jhipster/generator-jhipster/blob/a88374f1001e82177540b7d57ada6a56291f3ca3/generators/client/templates/react/src/main/webapp/app/shared/util/url-utils.ts.ejs#L24)

##### **Reproduce the error**

Try:

```
npm install -g generator-jhipster-vuejs@1.0.0-beta.2
```

**Comment by ruddell** [comment]
The version on npm is `1.0.0-beta2` (or just use `beta`), found with `npm info generator-jhipster-vuejs`
```
npm install -g generator-jhipster-vuejs@1.0.0-beta2
```

**Comment by mraible** [comment]
@ruddell Thanks for the tip! Even after using the correct version number, when I run:

```
jhipster --blueprint vuejs
```

It still prompts me for Angular or React. Does the blueprint feature not work when using `npm link` on JHipster's master branch?

**Comment by atomfrede** [comment]
I think you have to link the blueprint before in your folder.
