### ISSUE TITLE
.mvnw results in issue on sonar-project.properties

### ISSUE THREAD

**Issue by Strat1987** [jhipster/jhipster-vuejs#365]
After using the blueprint and trying to initialize using ./mvnw
I get following BUILD FAILURE exception:

[INFO] --- properties-maven-plugin:1.0.0:read-project-properties (default) @ campusrecruitment ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.752 s
[INFO] Finished at: 2019-05-12T16:29:44+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:properties-maven-plugin:1.0.0:read-project-properties (default) on project campusrecruitment: Properties could not be loaded from File: /Users/userid/Documents/jhipstervuejs/sonar-project.properties -> [Help 1]

I can see this file was not created during project creation.
After manually creating a file named sonar-project.properties (even if empty) the ./mvnw does continue.

**Comment by sahbi-ktifa** [comment]
Hi, did you use the latest version of the blueprint or the latest beta tag?

**Comment by Strat1987** [comment]
Hi, I believe I've used 1.0.0-beta2, is there anyway for me to check?

**Comment by sahbi-ktifa** [comment]
It depends how you installed it first. We should do a release soon we tons of fix and also, compatibility with JHipster 6.0.x. This is your problem here, as 1.0.0-beta2 do not work with JHipster 6.

**Comment by sahbi-ktifa** [comment]
Hi @strat1987, you can now use the latest version.

**Comment by Strat1987** [comment]
Hi @sabrinapayet , Thanks for your effort! This issue is now resolved by rerunning
> yarn global upgrade generator-jhipster-vuejs
>  jhipster --blueprint vuejs
> .mvwn
[INFO] BUILD SUCCESS
