### ISSUE TITLE
Application not redirect path /oauth2 to server when using webpack

### ISSUE THREAD

**Issue by vinicius91carvalho** [jhipster/jhipster-vuejs#371]
##### **Overview of the issue**

When I running the webpack server with command `yarn start` and I logged with Keycloak, the parameter redirect_uri with initial path with '/oauth2' is callled from keycloak to application, no route was found.

##### **Motivation for or Use Case**

When I start a webserver to local develop features, I want to login and redirect me to the application normally.

##### **Reproduce the error**

1) Start keycloak
2) Start registry
3) Start gateway
4) Start front-end webpack server
5) Try to login with Keycloak
6) Redirect to app fails

##### **Suggest a Fix**

Add the line '/oauth2' in the `webpack.dev.js`

```
devServer: {
    contentBase: './build/resources/main/static/',
    port: 9060,
    proxy: [
      {
        context: [
          /* jhipster-needle-add-entity-to-webpack - JHipster will add entity api paths here */
          '/api',
          '/management',
          '/swagger-resources',
          '/v2/api-docs',
          '/h2-console',
          '/login',
          '/auth',
          '/oauth2'
        ],
        target: 'http://127.0.0.1:8080',
        secure: false,
        headers: { host: 'localhost:9000' }
      }
    ],
```

##### **JHipster Version(s)**

6.0.1

##### **JHipster Version(s)**

```
gateway@0.0.0 /Users/viniciuscarvalho/Projects/sbt-platform/gateway
└─┬ generator-jhipster-vuejs@1.0.0
  └── generator-jhipster@6.0.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "br.com.sbt.gateway",
      "nativeLanguage": "pt-br"
    },
    "jhipsterVersion": "6.0.1",
    "applicationType": "gateway",
    "baseName": "gateway",
    "packageName": "br.com.sbt.gateway",
    "packageFolder": "br/com/sbt/gateway",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": "kafka",
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "testFrameworks": ["gatling", "protractor"],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [
      {
        "name": "generator-jhipster-vuejs",
        "version": "1.0.0"
      }
    ],
    "enableTranslation": true,
    "clientPackageManager": "npm",
    "nativeLanguage": "pt-br",
    "languages": ["pt-br", "en"],
    "blueprint": "generator-jhipster-vuejs",
    "blueprintVersion": "1.0.0"
  },
  "generator-jhipster-vuejs": {
    "jhipsterVersion": "6.0.1",
    "applicationType": "gateway",
    "baseName": "gateway",
    "clientFramework": "vue",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "useSass": true,
    "clientPackageManager": "npm"
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

git version 2.21.0

node: v10.15.3

npm: 6.9.0

yeoman: 2.0.0

yarn: 1.15.2

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01

##### **Browsers and Operating System**

MacOS Mojave 10.14.5
Versão 74.0.3729.169 (Version official) 64 bits

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
In the main generator for HTML5 Mode (https://github.com/jhipster/generator-jhipster/pull/9098), I changed the webpack proxy to `/` instead of a list of routes.  This should fix the above issue.

You can compare the differences - [vuejs webpack.dev.js](https://github.com/jhipster/jhipster-vuejs/blob/77d27c89f4f80958e56ee8af0d00759f05591b1a/generators/client/templates/vue/webpack/webpack.dev.js.ejs#L37-L46), [angular webpack.dev.js](https://github.com/jhipster/generator-jhipster/blob/301e1cc084a35b447602c0bd9dc21f0b83f6cad0/generators/client/templates/angular/webpack/webpack.dev.js.ejs#L40-L42)

**Comment by vinicius91carvalho** [comment]
@ruddell Thanks for your answer. [This change](https://github.com/jhipster/generator-jhipster/blob/301e1cc084a35b447602c0bd9dc21f0b83f6cad0/generators/client/templates/angular/webpack/webpack.dev.js.ejs#L40-L42) of all routes aiming to server will works only whether front-end will be running on server in the same port?
For the front-end running on port 9000 and the back-end on port 8080 I think that it will not works, because without '#' on the url, all routes from the front-end will be send to the server on the port 8080 and not to port 9000 where the webpack will be running.
