### ISSUE TITLE
Error while using Keycloak with JHipster 5.8.0

### ISSUE THREAD

**Issue by sreerajr137** [jhipster/jhipster-vuejs#377]
I created one microservice application using JHipster , with keycloak oAuth2 server. Then trying to signup error is showing
Error occured while trying to proxy to: localhost:9000/oauth2/authorization/oidc 

JHipster + keycloak + angular able to sign up and  its working fine, but not working with vue js?

**Comment by ruddell** [comment]
You can copy the solution from https://github.com/jhipster/jhipster-vuejs/pull/378/files, I believe that should work

**Comment by hdurix** [comment]
If this fix works for you @sreerajr137, it will be fixed by https://github.com/jhipster/jhipster-vuejs/pull/378.

**Comment by sahbi-ktifa** [comment]
Hum that's many people who encounter that issue. Let's merge this as this is the solution in the main generator.

**Comment by sahbi-ktifa** [comment]
@sreerajr137 Could you try again please with the fix now provided ?

**Comment by sahbi-ktifa** [comment]
@sreerajr137 I noticed the JHipster version you mentionned. Latest version of this blueprint uses JHipster 6.0.X, if you'd like to use a prior version, please use blueprint version prior 1.0.0 release (but I can only advise you to use our latest versions^^)

**Comment by sreerajr137** [comment]
Its not working with latest version(6.0.2) also...

**Comment by sahbi-ktifa** [comment]
Are you using the latest blueprint version or the master branch of it? This should be fixed within the master branch? If so, I could do a release soon.

Thank you for your feedbacks

**Comment by sreerajr137** [comment]
##### **JHipster Version(s)**
-- generator-jhipster-vuejs@1.0.0
-- generator-jhipster@6.0.1

**Comment by sahbi-ktifa** [comment]
Ok, so it should be fixed within the next blueprint release. Check #378 for quick fix if you want.

**Comment by sahbi-ktifa** [comment]
As there is no more updates on this, I close.
