### ISSUE TITLE
Update to use Typescript with TSX

### ISSUE THREAD

**Issue by deepu105** [jhipster/jhipster-vuejs#4]
- [ ] Replace babel with typescript compiler
- [ ] Use the VueCLI where possible to setup everything
- [ ] Tsx or html for templates
- [ ] Setup Tslint , prettier (copy from React config if possible)

**Comment by gurbirdhillon** [comment]
@deepu105 i can work on this one.

**Comment by deepu105** [comment]
Sure go ahead

**Comment by clarenced** [comment]
@gurbirdhillon did you advance on this issue ?

**Comment by deepu105** [comment]
@gurbirdhillon are you working on this? else please let us know so that someone else can take it up

**Comment by gurbirdhillon** [comment]
@deepu105 sorry i was busy lately, i can make sometime on this weekend if no one else available to take this one.

**Comment by hdurix** [comment]
We've started working on that with @gnuk, there is a lot to do, I will create a WIP PR soon.

**Comment by clarenced** [comment]
Hi @gurbirdhillon , I can work on this issue
