### ISSUE TITLE
no response after select the application type

### ISSUE THREAD

**Issue by shougao** [jhipster/jhipster-vuejs#400]
after upgrade hipster from 5.8 to 6.1, i got the issue.
below is the command line display.

ericmac:citicbackend eric$ jhipster --blueprint vuejs
INFO! No custom command found within blueprint: generator-jhipster-vuejs
INFO! Using JHipster version installed globally
INFO! Running default command
INFO! Executing jhipster:app
INFO! Options: blueprint: vuejs, from-cli: true

                            https://www.jhipster.tech

Welcome to JHipster v6.1.0
Application files will be generated in folder: /Users/eric/Development/jhipster/citicbackend
 ___________________________________________________________________________________________________________

  Documentation for creating an application is at https://www.jhipster.tech/creating-an-app/
  If you find JHipster useful, consider sponsoring the project at https://opencollective.com/generator-jhipster
 ___________________________________________________________________________________________________________

? Which *type* of application would you like to create? Monolithic application (recommended for simple projects)
? What is the base name of your application? (citicbackend) 

freeze here , even enter, esc, ctrl + z, ctrl + d, ctrl + c, and so on .

**Comment by pascalgrimaud** [comment]
the problem has been reported here: https://github.com/jhipster/generator-jhipster/issues/9952

The fix has been found, and we'll try to do a release soon

**Comment by hdurix** [comment]
I reopen this issue until this is fixed.

 @pascalgrimaud what should be the fix in the blueprint? Only upgrading to latest generator should be enough or do we have to fix the `inquirer` npm transitive dependency?

**Comment by pascalgrimaud** [comment]
@durix : I think both, but I'm not sure

**Comment by hdurix** [comment]
I'm not sure we have to do anything on the blueprint.
@shougao can you upgrade to the latest version of generator-jhipster (6.1.1) and retry please?

```
npm i -g generator-jhipster
```

**Comment by pascalgrimaud** [comment]
closing this, as it has been fixed
