### ISSUE TITLE
FR: Vuetify.js based version

### ISSUE THREAD

**Issue by 62mkv** [jhipster/jhipster-vuejs#408]
##### **Overview of the feature request**

There's a (as some people think) rather cool library called *Vuetify* (https://vuetifyjs.com/en/)

Maybe there's something in having a Vuetify-based version of this Blueprint ? Or should it be separate blueprint ? 

##### **Motivation for or Use Case**

I can't say that this is too important for us right now, but we're currently considering migration of our Vuejs-blueprint-based JHipster app frontend to Vuetify-based, and thought it might be nice if there was an option to use Vuetify-based generated frontend instead of current Bootstrap-based.

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
I think it should be a separate module/blueprint. Adding another ui framework/library would make our templates a lot more complicated and very hard to maintain. I don't see how we should do that.

**Comment by ivangsa** [comment]
I've made some work for a vuetify blueprint based on this one but almost forgot about it... 

it's not complete or up to date but there is plenty of work done
https://github.com/ivangsa/jhipster-vuetify

Typescript code is mostly compatible (with first betas of this blueprint), except for pagination and validation that can be handled with two mixins, and templates have been renamed so pulling back future upstream changes should be easy
If there is enough intereset (and help) I might retake it..

**Comment by ivangsa** [comment]
https://github.com/ivangsa/jhipster-vuetify-sample

**Comment by deepu105** [comment]
The core team will not be able to support another UI framework. You are welcome to build/maintain a blueprint for that.
