### ISSUE TITLE
Add ElasticSearch support on entities

### ISSUE THREAD

**Issue by sahbi-ktifa** [jhipster/jhipster-vuejs#41]

**Comment by pascalgrimaud** [comment]
@sahbi-ktifa : can I take this ticket ? It will help me to start contributing and learn VueJS

**Comment by sahbi-ktifa** [comment]
Sure, go ahead!

**Comment by pascalgrimaud** [comment]
can you assign this to me ?

**Comment by pascalgrimaud** [comment]
@deepu105 : as I plan to help this project, can I become contributor plz ? So I can review / assign / merge pull request. Thanks in advance! :heart:

**Comment by deepu105** [comment]
@pascalgrimaud arent you already a contributor? I guess only Julien can manage teams. @jdubois can you add core members to this project as well

**Comment by jdubois** [comment]
Yes it's a different team! @pascalgrimaud I just gave you access

**Comment by pascalgrimaud** [comment]
thanks a lot guys !

**Comment by pascalgrimaud** [comment]
sorry it's not the subject of this ticket, but it would be nice to add @hdurix to VueJS team too, if possible :)
