### ISSUE TITLE
[BUG] The admin audits page froze after clicking on the user or status columns

### ISSUE THREAD

**Issue by fleboulch** [jhipster/jhipster-vuejs#414]
##### **Overview of the issue**

The admin page froze after clicking on the user (or status) column. The dropdown on entity and admin on the navbar are also stuck.

##### **Motivation for or Use Case**

In the chrome console there is an error (see screenshot below)
![image](https://user-images.githubusercontent.com/9569081/60581584-67417680-9d87-11e9-983d-4527df02756b.png)

##### **Reproduce the error**

1. Go on the admin audits page
2. Click on the user (or status) column to sort
3. Try to click on the entity or admin menu (on the navbar) --> KO

##### **Related issues**
None

##### **Suggest a Fix**

I will try to do a PR next week to fix this

##### **JHipster configuration**

Same as #404 

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by fleboulch** [comment]
I didn't succeed to reproduce my own issue today.. That's really weird (I didn't update anything)...
Is someone able to reproduce it ?

**Comment by ruddell** [comment]
I couldn't reproduce but I do see a different error if the dates are the same:
```
vue.esm.js?a026:628 [Vue warn]: Duplicate keys detected: '2019-07-05T14:42:57Z'. This may cause an update error.
found in
---> <JhiAudits> at src/main/webapp/app/admin/audits/audits.vue
       <App> at src/main/webapp/app/app.vue
         <Root>
```

**Comment by fleboulch** [comment]
I'm closing this issue as I'm not able to reproduce it.
@ruddell I didn't succeed to reproduce your issue with same dates
