### ISSUE TITLE
Documentation - mention that Yeoman is a prerequisite

### ISSUE THREAD

**Issue by michaelisvy** [jhipster/jhipster-vuejs#427]
##### mention that Yeoman is a prerequisite

Hi, 
first of all, thanks a lot for the awesome work on JHipster! We use Vue.js in some of our applications and I was thrilled to see that JHipster has support for that.

I'd like to suggest a tiny improvement. The current documentation does not list `Yeoman` as a prerequisite to run `jhipster --blueprint vuejs`.
I didn't know about it and the error message was a bit misleading so it took me a while to understand that I needed to have yeoman installed. 

Proposed fix: add the below to the `Prerequisites` section
`Make sure you have Yeoman installed. If not, just run npm install -g yo`

Regards,
Michael.

**Comment by ruddell** [comment]
This should no longer be necessary on the next JHipster release https://github.com/jhipster/generator-jhipster/pull/10004

**Comment by michaelisvy** [comment]
that's great to know, thanks for the update!

**Comment by atomfrede** [comment]
I think we can close this right? The main generator has been released with that change.

**Comment by pascalgrimaud** [comment]
right, let's close this
