### ISSUE TITLE
Add MongoDB and Cassandra in travis/azure test automation

### ISSUE THREAD

**Issue by pmverma** [jhipster/jhipster-vuejs#435]
##### **Overview of the feature request**

Add travis/azure tests for `'cassandra', 'mongodb', 'couchbase'`
##### **Motivation for or Use Case**

I am doing a PR at https://github.com/jhipster/jhipster-vuejs/pull/434 and hence would like to have validated against all DBs types.

Was there any issue for these DBs or simply not added yet?
If it is the latter case, I can do a PR.

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Plz, I'd prefer Azure, rather than Travis, as we'll remove the builds with Travis

**Comment by pmverma** [comment]
Of course, Travis tests should be removed as they are so slow.
