### ISSUE TITLE
Quasar Framework

### ISSUE THREAD

**Issue by yuniel-acosta** [jhipster/jhipster-vuejs#440]
##### **Overview of the feature request**
Be able to generate the app using vuejs together with quasar framework

Give the possibility of generating the app with quasar as an alternative option to boostrap
##### **Motivation for or Use Case**
Quasar framework is a very good option which allows the creation of apps made with vuejs that compile any architecture using electron and cordova. It also has a set of components based on material design that are very attractive.

With quasar framework we can program using our graphic interface once and compile it both for a web application, such as PWA, as a Desktop application for Windows, Linux and MacOS using electron. It also allows us to compile for mobile platforms such as Android and IOS using cordova
##### **Related issues or PR**

-   [+] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
Hi @yuniel-acosta,

all our frontends are based on bootstrap and maintaining multiple templates depending on the frontend framework is way too much effort as we all do this in our freetime. So sorry there won't be a quasar option.
