### ISSUE TITLE
Blueprint needs update to 6.3 after CWE-338 disclosed

### ISSUE THREAD

**Issue by antonioortizpola** [jhipster/jhipster-vuejs#450]
##### **Overview of the issue**

We need to be able to update the app to 6.3 ASAP because of a high risk, security vulnerability disclosed in [JHipster Generator](https://github.com/jhipster/generator-jhipster/issues/10401).

##### **Motivation for or Use Case**
I would normally not pressure for an update after just 3 days, but since this is a security update, I think it would help to bring attention.

I checked a pull request to [bump to 6.3](https://github.com/jhipster/jhipster-vuejs/pull/449), but it has the builds failing.

##### **Related issues**

https://github.com/jhipster/generator-jhipster/security/advisories/GHSA-mwp6-j9wf-968c
https://github.com/jhipster/jhipster-vuejs/pull/449

##### **Suggest a Fix**

I can see the JHipster 6.3 is using now the `--blueprints` option (note the S, I am guessing to handle several blueprints), so maybe more changes are required. Sadly I do not know much about the blueprint internals, and seeing the need to update quick I wanted to ask if someone is checking this already with more knowledge than me.

If nobody is taking care of the update I could check in the week if I have time, but I do not promise much (Very new with Vue).

##### **JHipster Version(s)**

6.3

**Comment by pascalgrimaud** [comment]
Thanks for opening this ticket @antonioortizpola
Vue.js blueprint will generate only the front part. The backend is the one, generated by main generator-jhipster, so here the 6.3.0

Anyway, it would be cool to do a release soon, I'll try to do it soon :-)

**Comment by antonioortizpola** [comment]
The problem is that I think there was more changes in the branch, since yesterday I tried to generate a project with 6.3 but it failed to run, I just notice the changes to the "blueprints" option, so I was wondering if there was more changes.

I will check the errors and check if I there are more information

**Comment by antonioortizpola** [comment]
Ok, I have tried in a new computer with a new environment and everything worked fine, maybe the update broke something in my other PC, so sorry for the premature issue.

The only thing could be for now the update for the readme, so it uses the `blueprints` option instead `blueprint` to avoid a warining

**Comment by pascalgrimaud** [comment]
no worry, thanks for giving feedbacks
let's keep it opened until the next release, as it is important

**Comment by atomfrede** [comment]
I think we can close this as 1.2.0 is compatible with 6.4.1 already @pascalgrimaud

**Comment by antonioortizpola** [comment]
I have some pending updates, I was waiting for the generator to be updated, thanks a lot!

**Comment by antonioortizpola** [comment]
Sorry, wrong button, but I think is good for this issue to be closed
