### ISSUE TITLE
Sort icon in tables should indicate if the order applies to the column and the direction

### ISSUE THREAD

**Issue by antonioortizpola** [jhipster/jhipster-vuejs#456]
##### **Overview of the feature request**

I think the UX could improve a lot if we include an indicator of which column is used for the order, and which direction is used (ASC or DESC).

I fixed in my personal project with a little change:

From

`<th v-on:click="changeOrder('enabled')"><span v-text="$t('carwashApp.vehicleColor.enabled')">Enabled</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>`

To

```
<th v-on:click="changeOrder('enabled')">
    <span v-text="$t('carwashApp.vehicleColor.enabled')">Enabled</span>
    <i class="fas" v-bind:class="propOrder === 'enabled' ? (reverse ? 'fa-sort-down' : 'fa-sort-up') : 'fa-sort'"></i>
</th>
```

This way we have 3 indicators:

No sort

![Screenshot from 2019-09-29 15-40-42](https://user-images.githubusercontent.com/11655127/65839085-92c4f600-e2cf-11e9-97cb-3aa20479cc75.png)

Sort asc

![Screenshot from 2019-09-29 15-40-22](https://user-images.githubusercontent.com/11655127/65839096-bc7e1d00-e2cf-11e9-9d65-445d77c7cc11.png)

And sort desc

![Screenshot from 2019-09-29 15-40-32](https://user-images.githubusercontent.com/11655127/65839095-b5efa580-e2cf-11e9-9c48-260dfbc53175.png)

If you like it, I could prepare a pull request to change the generator, I would use the `font-awesome-icon`, adding the missing icons.

##### **Motivation for or Use Case**

Right now there is no way to check easily which column is selected for the order, this causes confusions and extra clicks to be sure.

##### **Related issues or PR**

I did not found anything open with "sort", "desc", or similar.

-   [ X ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
LGTM, yes, you're welcome to contribute !

**Comment by antonioortizpola** [comment]
Ok,I will work in this during the week in my free time

**Comment by antonioortizpola** [comment]
I made a pull request, but I think master is not working, in local and in the test, there is some error (before I modify anything)

```
##[section]Starting: GENERATION: jhipster info
==============================================================================
Task         : Bash
Description  : Run a Bash script on macOS, Linux, or Windows
Version      : 3.151.3
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
==============================================================================
Generating script.
Script contents:
$HOME/generator-jhipster/test-integration/scripts/14-jhipster-info.sh
========================== Starting Command Output ===========================
[command]/bin/bash --noprofile --norc /home/vsts/work/_temp/478f4dc5-93e5-4d7b-81e4-71c9387197bc.sh
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/vsts/generator-jhipster/cli/jhipster.js:20:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
##[error]Bash exited with code '1'.
##[section]Finishing: GENERATION: jhipster info
```

**Comment by atomfrede** [comment]
I made it working locally by doing `npm ci` on `generator-jhipster` and linking the project against that *again* but not sure why it is not working in ci.

**Comment by pascalgrimaud** [comment]
the npm link failed because the version is different between the one used by the CI, and the one inside package.json

we need to upgrade generator-jhipster to v6.3.1

**Comment by atomfrede** [comment]
I thought so. Will try to do it this evening.
