### ISSUE TITLE
Auth token is null in swagger

### ISSUE THREAD

**Issue by antonioortizpola** [jhipster/jhipster-vuejs#457]
##### **Overview of the issue**

The services in the swagger docs can not be tested because there is no bearer.

![DeepinScreenshot_select-area_20190929230922](https://user-images.githubusercontent.com/11655127/65849033-4f3dac80-e30e-11e9-9826-55de38e0f377.png)

##### **Motivation for or Use Case**

The user must have the possibility to test the API from the swagger docs.

##### **Reproduce the error**

Create any project and call any service from the swagger docs.

##### **Related issues**

I did not found.

##### **Suggest a Fix**

I have not much knowledge of how swagger is handled, but if I have time in the week I will investigate.

##### **JHipster Version(s)**

6.3

##### **JHipster configuration**

Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
carwash@0.0.0 /home/antonio/Projects/Carwash/project3/carwash
└─┬ generator-jhipster-vuejs@1.1.0
  └── generator-jhipster@6.1.2 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "bjt",
    "languages": ["en", "es"],
    "messageBroker": false,
    "nativeLanguage": "en",
    "packageName": "com.bejoto.carwash",
    "packageFolder": "com/bejoto/carwash",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "serviceDiscoveryType": false,
    "skipClient": false,
    "skipServer": false,
    "testFrameworks": [],
    "websocket": false,
    "baseName": "carwash",
    "buildTool": "gradle",
    "clientFramework": "vuejs",
    "jhipsterVersion": "6.3.1",
    "skipUserManagement": false,
    "clientPackageManager": "npm",
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "serverPort": "8080",
    "useSass": true,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "embeddableLaunchScript": false,
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [
      {
        "name": "generator-jhipster-vuejs",
        "version": "1.1.0"
      }
    ],
    "blueprints": [
      {
        "name": "generator-jhipster-vuejs",
        "version": "1.1.0"
      }
    ]
  },
  "entities": [
    "VehicleType",
    "VehicleColor",
    "VehicleBrand",
    "Vehicle",
    "Product",
    "ServiceForSale",
    "Client",
    "Sale",
    "SaleProductRecord",
    "SaleServiceForSaleRecord",
    "SaleLog"
  ],
  "generator-jhipster-vuejs": {
    "jhipsterVersion": "6.1.2",
    "applicationType": "monolith",
    "baseName": "carwash",
    "useSass": true,
    "enableTranslation": true,
    "clientPackageManager": "npm",
    "clientFramework": "vuejs",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "languages": ["en", "es"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity VehicleType {
  name String required minlength(1) maxlength(500),
  enabled Boolean required
}
entity VehicleColor {
  name String required minlength(1) maxlength(500),
  hexColor String required minlength(6) maxlength(6),
  enabled Boolean required
}
entity VehicleBrand {
  name String required minlength(1) maxlength(500),
  enabled Boolean required
}
entity Vehicle {
  plate String required minlength(1) maxlength(500),
  created Instant required,
  lastUpdate Instant required
}
entity Product {
  name String required minlength(1) maxlength(500),
  code String required minlength(1) maxlength(500),
  price BigDecimal required min(0),
  existence Integer required min(0),
  enabled Boolean required,
  created Instant required,
  lastUpdate Instant required
}
entity ServiceForSale {
  name String required minlength(1) maxlength(500),
  code String required minlength(1) maxlength(500),
  price BigDecimal required min(0),
  enabled Boolean required,
  created Instant required,
  lastUpdate Instant required
}
entity Client {
  name String required minlength(1) maxlength(500),
  email String minlength(1) maxlength(500),
  mobile String minlength(1) maxlength(500),
  enabled Boolean required,
  created Instant required,
  lastUpdate Instant required
}
entity Sale {
  clientName String minlength(1) maxlength(500),
  vehicleDescription String minlength(1) maxlength(500),
  total BigDecimal required min(0),
  status SaleStatus required,
  created Instant required,
  lastUpdate Instant required
}
entity SaleProductRecord {
  quantity Integer required min(0),
  price BigDecimal required min(0),
  name String required minlength(1) maxlength(500),
  code String required minlength(1) maxlength(500)
}
entity SaleServiceForSaleRecord {
  quantity Integer required min(0),
  price BigDecimal required min(0),
  name String required minlength(1) maxlength(500),
  code String required minlength(1) maxlength(500)
}
entity SaleLog {
  updated Instant required,
  observation String required minlength(1) maxlength(500)
}
enum SaleStatus {
  OPEN,
  CLOSED,
  CANCELED
}

relationship OneToMany {
  Client{vehicle} to Vehicle{client},
  Client{sale} to Sale{client},
  Vehicle{sale} to Sale{vehicle},
  Sale{saleProductRecord} to SaleProductRecord{sale},
  Sale{saleServiceForSaleRecord} to SaleServiceForSaleRecord{sale},
  Sale{saleLog} to SaleLog{sale}
}
relationship ManyToOne {
  Vehicle{vehicleType(name)} to VehicleType,
  Vehicle{vehicleColor(name)} to VehicleColor,
  Vehicle{vehicleBrand(name)} to VehicleBrand
}
relationship ManyToMany {
  ServiceForSale{vehicleType} to VehicleType{serviceForSale}
}

dto VehicleType, VehicleColor, VehicleBrand, Vehicle, Product, ServiceForSale, Client, Sale, SaleProductRecord, SaleServiceForSaleRecord, SaleLog with mapstruct
paginate VehicleType, VehicleColor, VehicleBrand, Vehicle, Product, ServiceForSale, Client, Sale, SaleProductRecord, SaleServiceForSaleRecord, SaleLog with pagination
service VehicleType, VehicleColor, VehicleBrand, Vehicle, Product, ServiceForSale, Client, Sale, SaleProductRecord, SaleServiceForSaleRecord, SaleLog with serviceClass
search Vehicle, Product, ServiceForSale, Client with elasticsearch

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.4+11, mixed mode)

git version 2.17.1

node: v10.16.3

npm: 6.9.0

yeoman: 3.1.0

Docker version 19.03.2, build 6a30dfc

docker-compose version 1.24.1, build 4667896b

##### **Browsers and Operating System**

Tested in Firefox and Ubuntu

-   [ X ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
It's surprising, as I'm using Vue.js for my current client and I don't encounter this problem

I need to try to reproduce your issue

**Comment by clement26695** [comment]
I managed to reproduce. It comes from the use of Elasticsearch. I'll try to investigate further

**Comment by clement26695** [comment]
After a bit more investigation, it appears that it does not work either with Angular when Elasticsearch is enabled

**Comment by clement26695** [comment]
Really strange, now I cannot reproduce, don't know what happened...

**Comment by antonioortizpola** [comment]
I created the project several times, I even removed and reinstalled JHipster and the Vuejs blueprint, but with no luck, could be something with my JDL?

I created my project with

`jhipster --blueprints vuejs import-jdl jhipster-carwash.jdl`

The full JDL is:

```
application {
  config {
    baseName carwash
    buildTool gradle
    devDatabaseType postgresql
    prodDatabaseType postgresql
    clientFramework vuejs
    jhiPrefix bjt
    languages [en, es]
    searchEngine elasticsearch
    packageName com.bejoto.carwash
    
  }
  entities *
}

DEFAULT_MIN_LENGTH = 1
DEFAULT_MAX_LENGTH = 500


// -----------------------------------
// ********** Vehicles **********

entity VehicleType {
  name String required minlength(DEFAULT_MIN_LENGTH) maxlength(DEFAULT_MAX_LENGTH)
  enabled Boolean required
}

entity VehicleColor {
  name String required minlength(DEFAULT_MIN_LENGTH) maxlength(DEFAULT_MAX_LENGTH)
  hexColor String required minlength(6) maxlength(6)
  enabled Boolean required
}

entity VehicleBrand {
  name String required minlength(DEFAULT_MIN_LENGTH) maxlength(DEFAULT_MAX_LENGTH)
  enabled Boolean required
}

entity Vehicle {
  plate String required minlength(DEFAULT_MIN_LENGTH) maxlength(DEFAULT_MAX_LENGTH)
  created Instant required
  lastUpdate Instant required
}

relationship ManyToOne {
  Vehicle{vehicleType(name)} to VehicleType
  Vehicle{vehicleColor(name)} to VehicleColor
  Vehicle{vehicleBrand(name)} to VehicleBrand
}


// ********** Products and services **********

entity Product {
  name String required minlength(DEFAULT_MIN_LENGTH) maxlength(DEFAULT_MAX_LENGTH)
  code String required minlength(DEFAULT_MIN_LENGTH) maxlength(DEFAULT_MAX_LENGTH)
  price BigDecimal required min(0)
  existence Integer required min(0)
  enabled Boolean required
  created Instant required
  lastUpdate Instant required
}

entity ServiceForSale {
  name String required minlength(DEFAULT_MIN_LENGTH) maxlength(DEFAULT_MAX_LENGTH)
  code String required minlength(DEFAULT_MIN_LENGTH) maxlength(DEFAULT_MAX_LENGTH)
  price BigDecimal required min(0)
  enabled Boolean required
  created Instant required
  lastUpdate Instant required
}

relationship ManyToMany {
  ServiceForSale to VehicleType
}


// ********** Clients **********

entity Client {
  name String required minlength(DEFAULT_MIN_LENGTH) maxlength(DEFAULT_MAX_LENGTH)
  email String minlength(DEFAULT_MIN_LENGTH) maxlength(DEFAULT_MAX_LENGTH)
  mobile String minlength(DEFAULT_MIN_LENGTH) maxlength(DEFAULT_MAX_LENGTH)
  enabled Boolean required
  created Instant required
  lastUpdate Instant required
}

relationship OneToMany {
  Client{vehicle} to Vehicle{client}
}


// ********** Order **********

enum SaleStatus {
  OPEN, CLOSED, CANCELED
}

entity Sale {
  clientName String minlength(DEFAULT_MIN_LENGTH) maxlength(DEFAULT_MAX_LENGTH)
  vehicleDescription String minlength(DEFAULT_MIN_LENGTH) maxlength(DEFAULT_MAX_LENGTH)
  total BigDecimal required min(0)
  status SaleStatus required
  created Instant required
  lastUpdate Instant required
}

entity SaleProductRecord {
  quantity Integer required min(0)
  price BigDecimal required min(0)
  name String required minlength(DEFAULT_MIN_LENGTH) maxlength(DEFAULT_MAX_LENGTH)
  code String required minlength(DEFAULT_MIN_LENGTH) maxlength(DEFAULT_MAX_LENGTH)
}

entity SaleServiceForSaleRecord {
  quantity Integer required min(0)
  price BigDecimal required min(0)
  name String required minlength(DEFAULT_MIN_LENGTH) maxlength(DEFAULT_MAX_LENGTH)
  code String required minlength(DEFAULT_MIN_LENGTH) maxlength(DEFAULT_MAX_LENGTH)
}

entity SaleLog {
  updated Instant required
  observation String required minlength(DEFAULT_MIN_LENGTH) maxlength(DEFAULT_MAX_LENGTH)
}

relationship OneToMany {
  Sale to SaleProductRecord
  Sale to SaleServiceForSaleRecord
}

relationship ManyToOne {
  SaleLog to Sale
  Sale to Client
  Sale to Vehicle
}


// -----------------------------------
// ********** Configuration **********

dto * with mapstruct
service * with serviceClass
paginate * with pagination
search Client, Product, ServiceForSale, Vehicle with elasticsearch
```

**Comment by hdurix** [comment]
Hi, I just found the explanation.

That's because you used a custom JHipster prefix (`jhiPrefix bjt` in your JDL) not handled in this blueprint as key for authentication token in the local/session storage but used for Swagger. I'll create the fix. Thanks for reporting this bug!
