### ISSUE TITLE
Edit entity is broken

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-vuejs#475]
It doesn't load the data, so the edit entity is broken

**Comment by pascalgrimaud** [comment]
INFO! Using JHipster version installed globally
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
jhipster@0.0.0 /home/pgrimaud/tmp/20-vuejs
└─┬ generator-jhipster-vuejs@1.1.0 -> /home/pgrimaud/projects/jhipster/jhipster-vuejs
  └── generator-jhipster@6.4.1 

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "io.github.jhipster.sample",
      "nativeLanguage": "en"
    },
    "applicationType": "monolith",
    "baseName": "jhipster",
    "packageName": "io.github.jhipster.sample",
    "packageFolder": "io/github/jhipster/sample",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "enableTranslation": true,
    "languages": [
      "en"
    ],
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "clientPackageManager": "npm",
    "nativeLanguage": "en",
    "blueprint": "generator-jhipster-vuejs",
    "clientFramework": "vue",
    "jhipsterVersion": "6.4.1",
    "embeddableLaunchScript": false,
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [
      {
        "name": "generator-jhipster-vuejs",
        "version": "1.1.0"
      }
    ],
    "blueprints": [
      {
        "name": "generator-jhipster-vuejs",
        "version": "1.1.0"
      }
    ]
  },
  "generator-jhipster-vuejs": {
    "applicationType": "monolith",
    "baseName": "jhipster",
    "clientFramework": "vue",
    "clientTheme": "none",
    "useSass": true,
    "clientPackageManager": "npm",
    "enableTranslation": true,
    "jhipsterVersion": "6.4.1",
    "languages": [
      "en"
    ]
  }
}
</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity BankAccount {
  name String required,
  guid UUID,
  bankNumber Integer,
  agencyNumber Long,
  lastOperationDuration Float,
  meanOperationDuration Double,
  meanQueueDuration Duration,
  balance BigDecimal required,
  openingDay LocalDate,
  lastOperationDate Instant,
  active Boolean,
  accountType BankAccountType,
  attachment AnyBlob,
  description TextBlob
}
entity Label {
  labelName String required minlength(3)
}
entity Operation {
  date Instant required,
  description String,
  amount BigDecimal required
}
enum BankAccountType {
  CHECKING,
  SAVINGS,
  LOAN
}

relationship OneToMany {
  BankAccount{operation} to Operation{bankAccount(name)}
}
relationship ManyToOne {
  BankAccount{user(login)} to User
}
relationship ManyToMany {
  Operation{label(labelName)} to Label{operation}
}

dto BankAccount with mapstruct
service BankAccount with serviceImpl
service Label with serviceClass
angularSuffix BankAccount with mySuffix
filter BankAccount
clientRootFolder BankAccount, Label, Operation with test-root
paginate Label with pagination
paginate Operation with infinite-scroll
readOnly Label

</pre>
</details>


##### **Environment and Tools**

openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3, mixed mode, sharing)

git version 2.23.0

node: v10.16.3

npm: 6.11.3

yeoman: 2.0.5

yarn: 1.19.1

Docker version 18.03.0-ce, build 0520e24

docker-compose version 1.21.2, build a133471

**Comment by nonomoho** [comment]
I propose a PR in few minutes!
