### ISSUE TITLE
EmailAlreadyUsedException not translated to client

### ISSUE THREAD

**Issue by weblogichub** [jhipster/jhipster-vuejs#500]
Just set same email on two users.
Submit button on form just disabled without any notification.

My config :

{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "org.jtoro",
      "nativeLanguage": "ru"
    },
    "jhipsterVersion": "6.5.1",
    "applicationType": "monolith",
    "baseName": "lib2",
    "packageName": "org.jtoro",
    "packageFolder": "org/jtoro",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "NDdkZmE0NDRiYWRkZjY5ZDAxMWU1NzY4NjFhMDI2YjhkYTRjNjU0MTNlZTRjZGFmZWZiY2JhYWRiN2M4YjA4MzhlZDQwY2M5N2RkZTdmYmQxYjM3MjQwNTJkZjUzZWNkNjExNDY3ZWYyZjk3MDk2YjBjYjdmOGQzY2MzZjMzNzQ=",
    "embeddableLaunchScript": false,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [
      {
        "name": "generator-jhipster-vuejs",
        "version": "1.2.0"
      }
    ],
    "enableTranslation": true,
    "clientPackageManager": "npm",
    "nativeLanguage": "ru",
    "languages": [
      "ru"
    ],
    "blueprints": [
      {
        "name": "generator-jhipster-vuejs",
        "version": "1.2.0"
      }
    ]
  },
  "generator-jhipster-vuejs": {
    "jhipsterVersion": "6.5.0",
    "applicationType": "monolith",
    "baseName": "lib2",
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "vue",
    "clientTheme": "none",
    "clientThemeVariant": ""
  }
}

**Comment by hdurix** [comment]
Thanks @weblogichub for the bug report. I just tested and this seems working now:

![image](https://user-images.githubusercontent.com/9678039/71512669-90a31100-2897-11ea-9f6c-e0c81cea4129.png)

Maybe this has been fixed since you created this issue. I'm closing the ticket then.
