### ISSUE TITLE
Delete alert confirmation is not correctly internationalized

### ISSUE THREAD

**Issue by weblogichub** [jhipster/jhipster-vuejs#501]
Delete alert confirmation is not correctly internationalized inside generated entity list vue components. Default value shown but i18n file has another value

![11111111111111111111111](https://user-images.githubusercontent.com/25816222/69502481-97093a80-0f31-11ea-8c3b-0ce5e963f251.png)

**Comment by pascalgrimaud** [comment]
@weblogichub : can you post the `jhipster info` output plz, so we can know which language you're using

**Comment by weblogichub** [comment]
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "org.jtoro",
      "nativeLanguage": "ru"
    },
    "jhipsterVersion": "6.5.1",
    "applicationType": "monolith",
    "baseName": "lib2",
    "packageName": "org.jtoro",
    "packageFolder": "org/jtoro",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "NDdkZmE0NDRiYWRkZjY5ZDAxMWU1NzY4NjFhMDI2YjhkYTRjNjU0MTNlZTRjZGFmZWZiY2JhYWRiN2M4YjA4MzhlZDQwY2M5N2RkZTdmYmQxYjM3MjQwNTJkZjUzZWNkNjExNDY3ZWYyZjk3MDk2YjBjYjdmOGQzY2MzZjMzNzQ=",
    "embeddableLaunchScript": false,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [
      {
        "name": "generator-jhipster-vuejs",
        "version": "1.2.0"
      }
    ],
    "enableTranslation": true,
    "clientPackageManager": "npm",
    "nativeLanguage": "ru",
    "languages": [
      "ru"
    ],
    "blueprints": [
      {
        "name": "generator-jhipster-vuejs",
        "version": "1.2.0"
      }
    ]
  },
  "generator-jhipster-vuejs": {
    "jhipsterVersion": "6.5.0",
    "applicationType": "monolith",
    "baseName": "lib2",
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "vue",
    "clientTheme": "none",
    "clientThemeVariant": ""
  }
}

**Comment by weblogichub** [comment]
Generated template contains :

                <p id="jhi-delete-libItemType-heading" v-bind:title="$t('lib2App.libItemType.delete.question')">Are you sure you want to delete this Lib Item Type?</p>

My fixed worked code like this :

                <p id="jhi-delete-libItemType-heading" v-text="$t('lib2App.libItemType.delete.question', {'id': removeId})">Are you sure you want to delete this Lib Item Type?</p>

**Comment by atomfrede** [comment]
Thanks @weblogichub for finding this. The fix looks correct, would you mind doing a PR for that?
