### ISSUE TITLE
Add release drafter

### ISSUE THREAD

**Issue by atomfrede** [jhipster/jhipster-vuejs#507]
##### **Overview of the feature request**

I think we should add https://github.com/apps/release-drafter to have better release notes without to much manual effort. With this we would have to categorize issues/prs correctly and have a release notes created automatically as draft we can still edit on the release day. [Here are the config options for github actions which are possible.](https://github.com/release-drafter/release-drafter)

##### **Motivation for or Use Case**

Currently the writing of release notes and changelogs is a manual process, which is error prone and takes time. As we all do it in our freetime every little part of automation helps.

##### **Related issues or PR**

We had a [similar discussion for the main generator](https://github.com/jhipster/generator-jhipster/issues/9853) but decided not to have it (yet) to have no multiple changelogs/release notes. But as we don't have a second release note place somewhere I think this might be evaluated here again. I like what e.g. testcontainers is doing https://github.com/testcontainers/testcontainers-java/releases.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
I think it's a good idea, @atomfrede and this project is perfect to give a try
I will install it on this project only and see how it works

**Comment by pascalgrimaud** [comment]
Just to let you know I'm trying to use this for the next release of jhipster-vuejs

**Comment by pascalgrimaud** [comment]
Here a first draft: https://github.com/jhipster/jhipster-vuejs/releases

**Comment by atomfrede** [comment]
Looks good for nearly unconfigured. Personally I like what [testcontainers](https://github.com/testcontainers/testcontainers-java/releases) are doing with [tagging](https://github.com/testcontainers/testcontainers-java/blob/master/.github/release-drafter.yml) MRs to differentiate the changes a little more. 

I think at least for features and bugfixes we can do that too.

**Comment by pascalgrimaud** [comment]
A 1st version is done, it can probably be improved but for now, I'm very happy with this.
Thanks @atomfrede

**Comment by atomfrede** [comment]
Nice, like it!
