### ISSUE TITLE
Unable to activate user - wrong URL

### ISSUE THREAD

**Issue by wortner** [jhipster/jhipster-vuejs#510]
##### **Overview of the issue**

Just generated jHipster app with Vuejs blueprint. Tried to register user which is working fine. Copied the url from register email shown in logs
http://127.0.0.1:8080/account/activate?key=DLs4RqK5zojMLqTs3Phw 
but got 404
the proper url seems to be 
http://127.0.0.1:8080/activate?key=DLs4RqK5zojMLqTs3Phw

##### **Motivation for or Use Case**

The user registration is not working.

##### **Reproduce the error**

Create new app with Vuejs blueprint

##### **JHipster configuration**

{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.5.1",
    "applicationType": "monolith",
    "baseName": "vue",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "ZjM0MTllODY1MzdlMTJjOTg5YWY2NTQwZTYyNTQzNTliNjZlNWE0YzFiN2YxYzdjNDNmNTM2MjEzMDllMGEwMzc4NGUzMTNlMTdlZWJiZTQyMmU4ZGY3ZDZjYmMxZjcwMTRkNWFmNDM2YmE0NTA0MTZlZmZjOWU1NThmNjBhYjM=",
    "embeddableLaunchScript": false,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [
      {
        "name": "generator-jhipster-vuejs",
        "version": "1.3.0"
      }
    ],
    "enableTranslation": true,
    "clientPackageManager": "npm",
    "nativeLanguage": "en",
    "languages": ["en", "cs"],
    "blueprints": [
      {
        "name": "generator-jhipster-vuejs",
        "version": "1.3.0"
      }
    ]
  },
  "generator-jhipster-vuejs": {
    "jhipsterVersion": "6.5.1",
    "applicationType": "monolith",
    "baseName": "vue",
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "vue",
    "clientTheme": "darkly",
    "clientThemeVariant": "dark"
  }
}

##### **Browsers and Operating System**

Widows 7, Chrome  78.0.3904.108

**Comment by wortner** [comment]
In regular angular based skeleton, the routing is set to "/account/activate". So the problem is probably in vue's router setup.

**Comment by atomfrede** [comment]
Thanks @wortner for reporting this. Indeed the route definition is [different](https://github.com/jhipster/jhipster-vuejs/blob/master/generators/client/templates/vue/src/main/webapp/app/router/index.ts.ejs#L71) from what we have in angular/react and in the backend. So I would suggest to align the routes with our other frontends. 

WDYT @jhipster/vuejs-developers ?

**Comment by pascalgrimaud** [comment]
+1
