### ISSUE TITLE
Protractor tests in current master

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-vuejs#516]
The protractor tests failed in current master branch.

It needed to be fixed.
I didn't have time to investigate, so I can't provide details here

**Comment by pascalgrimaud** [comment]
I'm adding a bounty as it is important to be fixed quickly

**Comment by kaidohallik** [comment]
Bounty claimed: https://opencollective.com/generator-jhipster/expenses/12614

**Comment by pascalgrimaud** [comment]
just approuved :)
