### ISSUE TITLE
User management edit component translation is not uniform

### ISSUE THREAD

**Issue by antonioortizpola** [jhipster/jhipster-vuejs#528]
##### **Overview of the issue**

The component it is not using translation consistently:

- It has validation messages ready for the inputs, but also has the property `maxlength` in the input, making the message unnecessary.
- The `maxlength` is not very user friendly, since it does not show errors to the user (Someone could be watching their keyboard and not notice how the input ignored the last keystrokes).
- It is not used in the entities, so, it is not consistent in all the application.

```
<input type="text" class="form-control" name="login"
       :class="{'valid': !$v.userAccount.login.$invalid, 'invalid': $v.userAccount.login.$invalid }"
       v-model="$v.userAccount.login.$model" required minlength="1" maxlength="50">

<div v-if="$v.userAccount.login.$anyDirty && $v.userAccount.login.$invalid">
    <small class="form-text text-danger"
           v-if="!$v.userAccount.login.required" v-text="$t('entity.validation.required')">
        This field is required.
    </small>

    <small class="form-text text-danger"
           v-if="!$v.userAccount.login.maxLength" v-text="$t('entity.validation.maxlength')">
        This field cannot be longer than 50 characters.
    </small>
```

The same for other fields like first and last names, also, the error message is not the same with or without translation, for example:

```
<small class="form-text text-danger"
       v-if="!$v.userAccount.firstName.maxLength" v-text="$t('entity.validation.maxlength')">
    Your first name cannot be longer than 50 characters.
</small>
```

The message with translation would be "This field cannot be longer than {{ max }} characters.", however, the message inside is " Your first name cannot be longer than 50 characters.", it would be great if the messages match.

Last, some messages are using i18n with `v-text` and it is working, but there are some others using `v-bind:value` and it is not translating:

```
<small class="form-text text-danger" v-if="!$v.client.email.maxLength" v-bind:value="$t('entity.validation.maxlength')">
    This field cannot be longer than 500 characters.
</small>
```

##### **Motivation for or Use Case**

The translation should work for all inputs, that is a fact, also, keeping the validation messages uniform can provide a better developer experience.

##### **Reproduce the error**

Generate a base JHipster project, go to user and change the language.

##### **Related issues**

I discovered this while working on #455

##### **Suggest a Fix**

If it seems good for you, I could add some fixes in the PR that I working for #455

##### **JHipster Version(s)**

6.6.0

##### **JHipster Version(s)**

```
carwash@0.0.0 /home/antonio/Projects/Carwash/carwash-jhipster-base
└─┬ generator-jhipster-vuejs@1.3.0 -> /home/antonio/Projects/JhipsterThings/jhipster-vuejs
  └── generator-jhipster@6.6.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "bjt",
    "languages": ["en", "es"],
    "messageBroker": false,
    "nativeLanguage": "en",
    "packageName": "com.bejoto.carwash",
    "packageFolder": "com/bejoto/carwash",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "serviceDiscoveryType": false,
    "skipClient": false,
    "skipServer": false,
    "testFrameworks": [],
    "websocket": false,
    "baseName": "carwash",
    "buildTool": "gradle",
    "clientFramework": "vuejs",
    "jhipsterVersion": "6.6.0",
    "skipUserManagement": false,
    "clientPackageManager": "npm",
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "serverPort": "8080",
    "useSass": true,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "embeddableLaunchScript": false,
    "creationTimestamp": 1578379476820,
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [
      {
        "name": "generator-jhipster-vuejs",
        "version": "1.3.0"
      }
    ],
    "blueprints": [
      {
        "name": "generator-jhipster-vuejs",
        "version": "1.3.0"
      }
    ]
  },
  "entities": [
    "VehicleType",
    "VehicleColor",
    "VehicleBrand",
    "Vehicle",
    "Product",
    "ServiceForSale",
    "Client",
    "Sale",
    "SaleProductRecord",
    "SaleServiceForSaleRecord",
    "SaleLog"
  ],
  "generator-jhipster-vuejs": {
    "jhipsterVersion": "6.6.0",
    "applicationType": "monolith",
    "baseName": "carwash",
    "useSass": true,
    "enableTranslation": true,
    "clientPackageManager": "npm",
    "clientFramework": "vuejs",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "languages": ["en", "es"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity VehicleType {
  name String required minlength(1) maxlength(500),
  enabled Boolean required
}
entity VehicleColor {
  name String required minlength(1) maxlength(500),
  hexColor String required minlength(6) maxlength(6),
  enabled Boolean required
}
entity VehicleBrand {
  name String required minlength(1) maxlength(500),
  enabled Boolean required
}
entity Vehicle {
  plate String required minlength(1) maxlength(500),
  created Instant required,
  lastUpdate Instant required
}
entity Product {
  name String required minlength(1) maxlength(500),
  code String required minlength(1) maxlength(500),
  price BigDecimal required min(0),
  existence Integer required min(0),
  enabled Boolean required,
  created Instant required,
  lastUpdate Instant required
}
entity ServiceForSale {
  name String required minlength(1) maxlength(500),
  code String required minlength(1) maxlength(500),
  price BigDecimal required min(0),
  enabled Boolean required,
  created Instant required,
  lastUpdate Instant required
}
entity Client {
  name String required minlength(1) maxlength(500),
  email String minlength(1) maxlength(500),
  mobile String minlength(1) maxlength(500),
  enabled Boolean required,
  created Instant required,
  lastUpdate Instant required
}
entity Sale {
  clientName String minlength(1) maxlength(500),
  vehicleDescription String minlength(1) maxlength(500),
  total BigDecimal required min(0),
  status SaleStatus required,
  created Instant required,
  lastUpdate Instant required
}
entity SaleProductRecord {
  quantity Integer required min(0),
  price BigDecimal required min(0),
  name String required minlength(1) maxlength(500),
  code String required minlength(1) maxlength(500)
}
entity SaleServiceForSaleRecord {
  quantity Integer required min(0),
  price BigDecimal required min(0),
  name String required minlength(1) maxlength(500),
  code String required minlength(1) maxlength(500)
}
entity SaleLog {
  updated Instant required,
  observation String required minlength(1) maxlength(500)
}
enum SaleStatus {
  OPEN,
  CLOSED,
  CANCELED
}

relationship OneToMany {
  Client{vehicle} to Vehicle{client},
  Sale{saleProductRecord} to SaleProductRecord{sale},
  Sale{saleServiceForSaleRecord} to SaleServiceForSaleRecord{sale}
}
relationship ManyToOne {
  Vehicle{vehicleType(name)} to VehicleType,
  Vehicle{vehicleColor(name)} to VehicleColor,
  Vehicle{vehicleBrand(name)} to VehicleBrand,
  Sale{client required} to Client,
  Sale{vehicle required} to Vehicle,
  SaleLog{sale required} to Sale
}
relationship ManyToMany {
  ServiceForSale{vehicleType} to VehicleType{serviceForSale}
}

dto VehicleType, VehicleColor, VehicleBrand, Vehicle, Product, ServiceForSale, Client, Sale, SaleProductRecord, SaleServiceForSaleRecord, SaleLog with mapstruct
paginate VehicleType, VehicleColor, VehicleBrand, Vehicle, Product, ServiceForSale, Client, Sale, SaleProductRecord, SaleServiceForSaleRecord, SaleLog with pagination
service VehicleType, VehicleColor, VehicleBrand, Vehicle, Product, ServiceForSale, Client, Sale, SaleProductRecord, SaleServiceForSaleRecord, SaleLog with serviceClass
search Vehicle, Product, ServiceForSale, Client with elasticsearch

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.5+10, mixed mode)

git version 2.17.1

node: v12.14.0

npm: 6.13.4

yeoman: 3.1.1

Docker version 19.03.5, build 633a0ea838

docker-compose version 1.24.1, build 4667896b

-   [ X ] Checking this box is mandatory (this is just to show you read everything)

**Comment by hdurix** [comment]
Thanks @antonioortizpola for this issue. Indeed there were a looooot of small issues both in user management and in entity management. I tried to resolve all in https://github.com/jhipster/jhipster-vuejs/pull/546
