### ISSUE TITLE
Support for JHipster UAA Server

### ISSUE THREAD

**Issue by petrroda** [jhipster/jhipster-vuejs#529]
##### **Overview of the feature request**

As the UAA Server is a standard component of the JHipster stack and is supported
with Angular and React, it will be time to implement an integration also for VueJS.

**Comment by pascalgrimaud** [comment]
The support of UAA in main generator-jhipster is not perfect, with a lot of flaky tests.
See https://dev.azure.com/hipster-labs/jhipster-daily-builds/_build?definitionId=18&_a=summary
A lot of failures since more than 1 year.

UAA is maintained by only 1 person, no one want to help in main generator-jhipster.

Sorry, that's the reason why UAA won't be supported in this blueprint.

**Comment by Brouilles** [comment]
UAA support is still not planned?

**Comment by pascalgrimaud** [comment]
@Brouilles : sorry, nobody want to contribute for this.. so no, it's not planned.

Plz, understand we do it only during our free and personal time: we are not paid for that. And as it's an option the "Vue.js contributors" don't use a lot, I don't think we'll do it on our side.

**Comment by Brouilles** [comment]
Hi @pascalgrimaud 
Thanks for your answer. Its seems you know very well the project.
I'm interested by this feature. Where should I start to work on integrating this functionality? Do you consider this a complex task?

Thanks!

**Comment by pascalgrimaud** [comment]
@Brouilles : as you would like to contribute, then I reopen the issue.
You can start to look at the main https://github.com/jhipster/generator-jhipster specially at the client files, to search where UAA is concerned. 
I think the main part is related to authentication, so you should look at there, first.

Then, you should generate a sample project with Vue.js, try to apply the correct modification to make it work with UAA. 
Once it's done, simply do the same in the template of Vue.js

**Comment by Brouilles** [comment]
See https://github.com/jhipster/jhipster-vuejs/pull/580

**Comment by mac8088** [comment]
@pascalgrimaud 
kindly ask the problem for the UAA support,  when will you deliver the next release?

**Comment by pascalgrimaud** [comment]
@mac8088 : there is no ETA, as it's an Open Source project and we work on this during our personal time, we're not paid for that :)
But as soon as UAA is reviewed, tested and merged, there should not be a problem. I think I can do a release.
So your help is welcome to test the PR

**Comment by mac8088** [comment]
@pascalgrimaud 

Thanks for your answer. The test of this PR is KO when I try to generate the new UAA project.

I checked out the @Brouilles  GIT Reps and made the code comparison, he added some logic checking for authenticationType !== 'uaa' or authenticationType === 'uaa' in 12 ejs template files.

My project generation was failed when I used the local Blueprint version for development (generator-jhipster v6.8.0 + jhipster-vuejs v1.7.0 + brouilles's changing code).

See some error info:

create src\main\webapp\app\shared\jhi-item-count.component.ts
create src\main\webapp\app\shared\model\user.model.ts
SyntaxError: Unexpected token. A constructor, method, accessor, or property was expected. (52:6)
  50 |       }
  51 |       this.translationService.refreshTranslation(this.store.getters.currentLanguage);
> 52 |     }).catch(() => {
     |      ^
  53 |       this.store.commit('logout');
  54 |       this.router.push('/');
  55 |     });
    at t (D:\microservices\generator-jhipster\node_modules\prettier\parser-typescript.js:1:285)
    at Object.parse (D:\microservices\generator-jhipster\node_modules\prettier\parser-typescript.js:14:180461)
    at Object.parse (D:\microservices\generator-jhipster\node_modules\prettier\index.js:9739:19)
    at coreFormat (D:\microservices\generator-jhipster\node_modules\prettier\index.js:13252:23)
    at format (D:\microservices\generator-jhipster\node_modules\prettier\index.js:13510:73)
    at formatWithCursor (D:\microservices\generator-jhipster\node_modules\prettier\index.js:13526:12)
    at D:\microservices\generator-jhipster\node_modules\prettier\index.js:44207:15
    at Object.format (D:\microservices\generator-jhipster\node_modules\prettier\index.js:44226:12)
    at D:\microservices\generator-jhipster\generators\generator-transforms.js:44:39

**Comment by pascalgrimaud** [comment]
@mac8088 : just close the other PR as it doesn't work.
Sorry for that but if you want to use UAA, you have to code it on your side as the support in Vue.js can't be done if no one want to contribute.

I'm removing the bounty but if someone wants to give a try, feel free to tell it, I can put it back.
For now, let's close this.
