### ISSUE TITLE
Sonar Analyze

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-vuejs#531]
Current Sonar Analyze for a Vue.js is not so good.
It should be AAA.

I can provide more details if needed.

**Comment by pascalgrimaud** [comment]
I'm adding a bounty on this as it's important to have it fixed.

**Comment by atomfrede** [comment]
Is this related to the sonar upstream issues? https://github.com/jhipster/jhipster-vuejs/issues/431

**Comment by pascalgrimaud** [comment]
no @atomfrede, I analyze a Vue.js gateway for my customer and there are a lot of issues and bugs
It's easy to fix them, so it can be an easy ticket for a new contributor. 
I was asking to @fdaudies : maybe she'll try to fix them :) 
Or another new contributor...

**Comment by fdaudies** [comment]
Thanks @pascalgrimaud , I'll try to work on this issue as a new contributor :)

**Comment by hdurix** [comment]
Don't hesitate to ping us @fdaudies :)

**Comment by skmaingi** [comment]
Seems like SonarQube doesn't yet support .vue
The problem being that it support single file components (SFC) i.e. Vue files aggregate in one file logic (javascript or typescript), style (css), and template (html).
https://community.sonarsource.com/t/sonarqube-scanner-fails-to-analyze-vue-files-failed-to-parse-file-vue/17751

**Comment by pascalgrimaud** [comment]
thanks for your comment @skmaingi and you're right ! 

but what you're talking about is related to this ticket https://github.com/jhipster/jhipster-vuejs/issues/431 and not to this one :-)

**Comment by pascalgrimaud** [comment]
It seems like @fdaudies doesn't have the time to do this.
Are you interested on this @skmaingi ? If yes, I'll assign this to you, and I can tell you the steps about the work to do here

**Comment by skmaingi** [comment]
@pascalgrimaud I am interested. Thank you

**Comment by pascalgrimaud** [comment]
@skmaingi : the steps are:
- generate a JHipster project with Vue.js
- start local Sonar instance
- launch Sonar analyze
- there is a lot of errors / issues, which can be easily fixed
- fix them in the generated project
- relaunch Sonar analyze
- then, report the appropriate change in blueprint Vue.js

**Comment by skmaingi** [comment]
@pascalgrimaud Thank you for the information. I'll work on it

**Comment by pascalgrimaud** [comment]
As no news from you, I unassigned the ticket

**Comment by qmonmert** [comment]
@pascalgrimaud I take this ticket

**Comment by pascalgrimaud** [comment]
Thanks a lot @qmonmert : I need this :)

**Comment by qmonmert** [comment]
PR https://github.com/jhipster/generator-jhipster/pull/12177

**Comment by qmonmert** [comment]
@pascalgrimaud I claim my money 😄 https://opencollective.com/generator-jhipster/expenses/22889
