### ISSUE TITLE
OAuth2 + MapsId

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-vuejs#532]
Our current CI failed because of that.
See https://dev.azure.com/jhipster/jhipster-vuejs/_build/results?buildId=8488

**Comment by pascalgrimaud** [comment]
Adding a bounty as it's important to be fixed before the next release !

**Comment by pascalgrimaud** [comment]
cc @hdurix, as I know you already have a look on this

**Comment by hdurix** [comment]
Should be fixed once https://github.com/jhipster/generator-jhipster/issues/11099 is merged and a new release for the generator is done.

**Comment by pascalgrimaud** [comment]
@hdurix : you pointed an issue, not a PR

**Comment by hdurix** [comment]
Here is the PR: https://github.com/jhipster/generator-jhipster/pull/11100

**Comment by pascalgrimaud** [comment]
done, the build is green  so we can close it
thanks @hdurix

**Comment by hdurix** [comment]
Bounty claimed: https://opencollective.com/generator-jhipster/expenses/13216
