### ISSUE TITLE
migration to bootstrap-vue icons

### ISSUE THREAD

**Issue by yetanothercoder** [jhipster/jhipster-vuejs#536]
##### **Overview of the feature request**

Recently icons package was added to BootstrapVue: https://bootstrap-vue.js.org/docs/icons - so it can be useful to migrate to them instead of FontAwesome ones.  

##### **Motivation for or Use Case**

1. improved a consistency with bootstrap
1. minimized the amount of dependencies and codebase. 
1. large amount of totally free icons (no issues with licenses), appendable in the future by BV releases

##### **Related issues or PR**

found some archived PRs related to issues with FA icons:
https://github.com/jhipster/jhipster-vuejs/pull/130
https://github.com/jhipster/jhipster-vuejs/pull/141

-   [x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
Thanks for the suggestion, but right now I don't think we will do that as all other frontends still use font awesome.

**Comment by atomfrede** [comment]
As we will not do it in vue.js alone and are quite happy with fontawesome I think we can close this for now. We can revisit bootstrap icons later if needed.
