### ISSUE TITLE
Password Reset Route Issue

### ISSUE THREAD

**Issue by skmaingi** [jhipster/jhipster-vuejs#538]
##### **Overview of the issue**

An error is thrown "The page you requested does not exist" when one clicks the url received for password reset.

##### **Motivation for or Use Case**

Users of VueJS web application generated generator-jhipster-vuejs are unable to reset password.

##### **Reproduce the error**

Generate application using generator-jhipster-vuejs with "jhipster --blueprint vuejs" command.

##### **Suggest a Fix**

Change router path from "/reset/finish" to "/account/reset/finish"

##### **JHipster Version(s)**

6.5.1

##### **JHipster Version(s)**

```
itracker@0.0.0 /home/ubuntu/JHipster/
└─┬ generator-jhipster-vuejs@1.3.0
  └── generator-jhipster@6.5.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": ""
    },
    "jhipsterVersion": "6.5.1",
    "applicationType": "monolith",
    "baseName": "",
    "packageName": "",
    "packageFolder": ",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "",
    "embeddableLaunchScript": false,
    "testFrameworks": ["gatling", "cucumber"],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [
      {
        "name": "generator-jhipster-vuejs",
        "version": "1.3.0"
      }
    ],
    "enableTranslation": false,
    "clientPackageManager": "npm",
    "blueprints": [
      {
        "name": "generator-jhipster-vuejs",
        "version": "1.3.0"
      }
    ],
    "herokuAppName": "",
    "herokuDeployType": "git"
  },
  "generator-jhipster-vuejs": {
    "jhipsterVersion": "6.5.1",
    "applicationType": "monolith",
    "baseName": "",
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "vue",
    "clientTheme": "solar",
    "clientThemeVariant": "primary"
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
.
.
.
</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

git version 2.7.4

node: v10.16.3

npm: 6.9.0

yeoman: 3.1.1

yarn: 1.17.3

Docker version 19.03.1, build 74b1e89e8a

docker-compose version 1.8.0, build unknown

##### **Browsers and Operating System**

Ubuntu 16.04.6 LTS

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
I think it's the same issue than https://github.com/jhipster/jhipster-vuejs/issues/510
It should be resolved by https://github.com/jhipster/jhipster-vuejs/pull/512 -> look at the diff https://github.com/jhipster/jhipster-vuejs/pull/512/files

Then, can you try the last release of Vue.js: 1.4.0 plz ?
If it's not fixed for you, I'll reopen the ticket.
