### ISSUE TITLE
Add test to check that beforeRouteEnter hooks are called in entity update components

### ISSUE THREAD

**Issue by stonedMoose** [jhipster/jhipster-vuejs#567]
##### **Overview of the issue**

In update entity components the entity being updated is fetched by using `beforeRouteEnter` hook.
There is no test to check that, while it should be. 

The goal here is to ensure that a call to the service is made when a user navigate to an update component. And that this call do update the underlying entity of the component.

##### **Motivation for or Use Case**

Improve the code coverage of the vuejs application.

##### **Related issues or PR**

An [issue involving yarn](https://github.com/jhipster/jhipster-vuejs/issues/565) has enlighten these missing tests.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by stonedMoose** [comment]
I think the problem here can be split in two:

* The first test should be to check that the router configuration allows the registered hooks to be triggered on navigation event. I'm not sure that it could be done with unit testing of one component in isolation of other components. Reading [the vue router test cookbook](https://lmiller1990.github.io/vue-testing-handbook/vue-router.html#creating-the-router-and-routes) it appears that navigation and associated event are tested using the App component, and verifying that it mounts the child component when needed.

* The second part, seems more easy to test (there is already some test that do simular checks). It consist on verifying that the `beforeRouteEnter` does what expected (ie. call the service, and update the component entity)

**Comment by pascalgrimaud** [comment]
I think this ticket will help for the upgrade to generator-jhipster 6.8.0

**Comment by pascalgrimaud** [comment]
Testing beforeRouteEnter should be easy.
If I remember well, we did it on our current project with @nonomoho -> can you confirm ?

So I should be able to take care of this, unless you want to lead this part @stonedMoose : just tell me :-)

**Comment by geyuqiu** [comment]
I get the impression that
currently `beforeRouteEnter` is not called: [reproduction see here](https://github.com/jhipster/jhipster-vuejs/issues/598)

neither in [entityName-]details.component.ts nor in [entityName-]update.component.ts

result in empty value fields


more information: 

jdl

```
entity Student {
	name String  required
}

entity University {
	name String  required
}

relationship OneToMany {
    University{standard} to Student{university(name) required},
}

dto * with mapstruct


``` 

<img width="1040" alt="Bildschirmfoto 2020-04-29 um 21 45 49" src="https://user-images.githubusercontent.com/4540661/80639812-d00a8580-8a62-11ea-95d0-5453c83805d0.png">

**Comment by pascalgrimaud** [comment]
done in main generator
