### ISSUE TITLE
Language json files HTTP caching strategy

### ISSUE THREAD

**Issue by fleboulch** [jhipster/jhipster-vuejs#585]
##### **Overview of the issue**

Language json files are cached in the browser for perfomance purpose. When I release a new version of my application (updating only wording in json files) and I pubished it, the new wording is not displayed because of cache. The user needs to do CTRL + SHIT + R for refreshing json resources (or even use anonymous mode).
##### **Motivation for or Use Case**

I checked for jhipster apps using angular for frontend and the behaviour is not the same. Indeed, the json file has a build timestamp key.
Ex for angular apps:
![image](https://user-images.githubusercontent.com/9569081/77254739-3e3d7a80-6c63-11ea-99df-a9567e8d813e.png)
Ex for vuejs apps:
![image](https://user-images.githubusercontent.com/9569081/77255113-747bf980-6c65-11ea-833d-add422220e3f.png)

##### **Reproduce the error**

Create app with the following JDL
```
application {  
    config {  
      baseName jhipster  
      packageName com.fleboulch.jhipster  
      buildTool gradle  
      databaseType sql  
      nativeLanguage fr  
      languages [fr]  
    }  
}
```
Run the import-jdl command with blueprints flag : `jhipster import-jdl jdl/app-jdl.jh --blueprints vuejs`
Run the app (with **prod** mode)  
Update `home.json` file with a different wording.
Re-run app and see the wording hasn't been updated
##### **Related issues**

None
##### **Suggest a Fix**

I checked webpack config in angular apps. The DefinePlugin from webpack is used to define a BUILD_TIMESTAMP constante. I tried to add this constante in vuejs project in `prod.env.js` file but it didn't solve the issue. I also check versions of different webpack plugins.

I'm not a webpack expert but I can try to help if someone knows how to fix it.
##### **JHipster Version(s)**

All

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
I confirm the issue and it's very annoying
I'm putting a bounty on this as it must be fixed. 

Maybe @wmarques you can help ?

**Comment by pascalgrimaud** [comment]
Sometimes, `CTRL + SHIFT + R` is not enough... it only works in private navigator

**Comment by wmarques** [comment]
I agree that we should add a hash on those files' names.
The other solution might be to serve the *.json files with no-cache headers so that they are never cached by the browser

**Comment by fleboulch** [comment]
@wmarques 
The second option should be easy to implement but performances should be impacted.  
I don't understand in Angular apps how we tell to webpack to add a hash on json resources.. I don't find how the BUILD_TIMESTAMP constante is added as key

**Comment by pascalgrimaud** [comment]
Maybe it has never be done like we did with Angular

**Comment by jdubois** [comment]
Long time ago, the first versions of JHipster did not cache those files... So 2 choices: either you don’t cache them, or put a hash with Webpack (better option, but more complex)

**Comment by fleboulch** [comment]
The solution to not cache json files is not good. Indeed, it requires to update the Spring Boot configuration. So the behaviour between Angular/React/VueJS won't be aligned and if VueJS is merged in the main generator (I don't know if this work is in progress or cancelled) it will be a regression...

The best solution is to cache this files by putting a hash with Webpack. I will try some stuff but I don't know a lot about webpack

**Comment by vishal423** [comment]
> I don't understand in Angular apps how we tell to webpack to add a hash on json resources.. I don't find how the BUILD_TIMESTAMP constante is added as key

I think you are looking out for [this](https://github.com/jhipster/ng-jhipster/blob/d8f9386c135b20aa5e3b415e91f0dcf34dddaa4d/src/ng-jhipster.module.ts#L33) reference

**Comment by fleboulch** [comment]
Thanks @vishal423. I didn't check into ng-jhipster dependency.
So it's not a webpack problem. I will further investigate and try to find a solution
