### ISSUE TITLE
Refresh same page: forbidden quick redirect

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-vuejs#587]
##### **Overview of the issue**

When refreshing a page, `forbidden` page appears (http://localhost:8080/forbidden), then we're redirected to the appropriated page.
So there is a glitch which is not cool.

##### **Reproduce the error**

refresh several time the same page once you're logged into the app

##### **JHipster Version(s)**

generator-jhipster@6.8.0
generator-jhipster-vuejs@1.7.0

➜ jhinfo       
INFO! Using JHipster version installed globally
INFO! No custom sharedOptions found within blueprint: generator-jhipster-vuejs at /home/pgrimaud/tmp/18-vuejs/node_modules/generator-jhipster-vuejs
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
jhipster@0.0.0 /home/pgrimaud/tmp/18-vuejs
└─┬ generator-jhipster-vuejs@1.7.0 -> /home/pgrimaud/projects/jhipster/jhipster-vuejs
  └── generator-jhipster@6.8.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "io.github.pascalgrimaud",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.8.0",
    "applicationType": "monolith",
    "baseName": "jhipster",
    "packageName": "io.github.pascalgrimaud",
    "packageFolder": "io/github/pascalgrimaud",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "vue",
    "clientTheme": "spacelab",
    "clientThemeVariant": "primary",
    "creationTimestamp": 1585551854646,
    "testFrameworks": ["gatling", "protractor"],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [
      {
        "name": "generator-jhipster-vuejs",
        "version": "1.7.0"
      }
    ],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en", "fr"],
    "blueprints": [
      {
        "name": "generator-jhipster-vuejs",
        "version": "1.7.0"
      }
    ]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Alpha {
  name String
}
dto Alpha with mapstruct
paginate Alpha with pagination
service Alpha with serviceClass

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1, mixed mode, sharing)

git version 2.26.0

node: v12.16.1

npm: 6.14.2

yeoman: 3.1.1

yarn: 1.22.4

Docker version 19.03.8, build afacb8b7f0

docker-compose version 1.21.2, build a133471

identical .jhipster/Alpha.json
INFO! Congratulations, JHipster execution is complete!

**Comment by pascalgrimaud** [comment]
adding a bounty on this, as it's a bug and it is very important to be fixed

**Comment by qmonmert** [comment]
@pascalgrimaud I claim my money 😄 https://opencollective.com/generator-jhipster/expenses/15676

**Comment by pascalgrimaud** [comment]
@qmonmert : approved

**Comment by qmonmert** [comment]
@pascalgrimaud merci :)
