### ISSUE TITLE
Entity page: default order should be asc

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-vuejs#596]
When you go to entity page, the entities is ordered by id + desc (reverse).
But the default value is set to `false`
See this https://github.com/jhipster/jhipster-vuejs/blob/master/generators/entity-client/templates/vue/src/main/webapp/app/entities/entity.component.ts.ejs#L25

It's related to this [line of code](https://github.com/jhipster/jhipster-vuejs/blob/master/generators/entity-client/templates/vue/src/main/webapp/app/entities/entity.component.ts.ejs#L189) :

```
const result = [this.propOrder + ',' + (this.reverse ? 'asc' : 'desc')];
```

Maybe tests needed to be fixed too

**Comment by qmonmert** [comment]
PR https://github.com/jhipster/generator-jhipster/pull/12189

cc @pascalgrimaud

**Comment by qmonmert** [comment]
@avdev4j you can close the ticket I think

**Comment by qmonmert** [comment]
@pascalgrimaud you can close the ticket I think: PR jhipster/generator-jhipster#12189
