### ISSUE TITLE
Migrate from tslint to eslint

### ISSUE THREAD

**Issue by ghost** [jhipster/jhipster-vuejs#597]
##### **Overview of the feature request**

Migrate linting from tslint to eslint for typescript.

##### **Motivation for or Use Case**

tslint is deprecated and eslint is recommended in its place.

##### **Related issues or PR**

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
it will be interesting to have, and be consistent with the main generator-jhipster 
- https://www.jhipster.tech/2019/09/13/jhipster-release-6.3.0.html
- https://github.com/jhipster/generator-jhipster/pull/10187
- https://github.com/jhipster/generator-jhipster/pull/10213

To be honest, it's a lot of work.
@hermitmaster : unless you want to do it, it won't be done, as we don't have enough contributors in Vue.js blueprint...

**Comment by atomfrede** [comment]
If no one is working on it I can have a look

**Comment by pascalgrimaud** [comment]
Closed by https://github.com/jhipster/generator-jhipster/pull/12972

**Comment by atomfrede** [comment]
Bounty claimed https://opencollective.com/generator-jhipster/expenses/27747

**Comment by pascalgrimaud** [comment]
@atomfrede : approved
