### ISSUE TITLE
Move the css hash stamped generated files to content directory when using prod profile

### ISSUE THREAD

**Issue by monxxi** [jhipster/jhipster-vuejs#599]
##### **Overview of the issue**
Based on the issue jhipster/generator-jhipster#11575 and the discussion in the PR related. 

We noticed a difference between the client VueJs  and the others (angular & React) concerning the locations of files css stamped with a hash.

With the VueJs Client: _**app.[hash].css, global.[hash].css and main.[hash].css**_ are present at the root of target/classes/static

```
$ ll ./target/classes/static/
total 524K
drwxr-xr-x 6 monxxi monxxi 4,0K avril 30 10:27 .
drwxr-xr-x 8 monxxi monxxi 4,0K avril 30 10:27 ..
drwxr-xr-x 2 monxxi monxxi 4,0K avril 30 10:27 app
-rw-r--r-- 1 monxxi monxxi 240K avril 30 10:27 app.d62967859bc49fb0216e.css
drwxr-xr-x 5 monxxi monxxi 4,0K avril 30 10:27 content
-rw-r--r-- 1 monxxi monxxi 1,6K avril 30 10:27 favicon.ico
-rw-r--r-- 1 monxxi monxxi 2,8K avril 30 10:27 global.0363758546bb34088f1c.css
drwxr-xr-x 2 monxxi monxxi 4,0K avril 30 10:27 i18n
-rw-r--r-- 1 monxxi monxxi 3,9K avril 30 10:27 index.html
-rw-r--r-- 1 monxxi monxxi 240K avril 30 10:27 main.d62967859bc49fb0216e.css
-rw-r--r-- 1 monxxi monxxi  881 avril 30 10:27 manifest.webapp
-rw-r--r-- 1 monxxi monxxi  239 avril 30 10:27 robots.txt
drwxr-xr-x 3 monxxi monxxi 4,0K avril 30 10:27 swagger-ui
```

With the Angular&React Client: these kind of css files are present in target/classes/static/content

- Angular => global.[hash].css , main.[hash].css 
- React => administration.[hash].css, main.[hash].css and vendors.[hash].css
```
./jhi-mono-angular/target/classes/static/content:
total 192K
drwxr-xr-x 5 monxxi monxxi 4,0K avril 30 12:43 .
drwxr-xr-x 6 monxxi monxxi 4,0K avril 30 12:43 ..
-rw-r--r-- 1 monxxi monxxi  605 avril 30 12:43 cfd81fbabebba3d187b7f0243b971186.png
drwxr-xr-x 2 monxxi monxxi 4,0K avril 30 12:43 css
-rw-r--r-- 1 monxxi monxxi  19K avril 30 12:43 dd126cd23626f52c91230a708bd6df77.svg
-rw-r--r-- 1 monxxi monxxi 1,6K avril 30 12:43 global.c5875b4a3bbc1ca82290.css
drwxr-xr-x 2 monxxi monxxi 4,0K avril 30 12:43 images
-rw-r--r-- 1 monxxi monxxi 142K avril 30 12:43 main.07b91d0f25a5e3ef8081.css
drwxr-xr-x 2 monxxi monxxi 4,0K avril 30 12:43 scss

./jhi-mono-react/target/classes/static/content:
total 196K
drwxr-xr-x 4 monxxi monxxi 4,0K avril 30 13:12 .
drwxr-xr-x 6 monxxi monxxi 4,0K avril 30 13:12 ..
-rw-r--r-- 1 monxxi monxxi  12K avril 30 13:12 068483b5e9a98559fe8b9755f577c433.svg
-rw-r--r-- 1 monxxi monxxi   23 avril 30 13:12 administration.21804302ada5ff1c5275.css
drwxr-xr-x 2 monxxi monxxi 4,0K avril 30 13:12 css
drwxr-xr-x 2 monxxi monxxi 4,0K avril 30 13:12 images
-rw-r--r-- 1 monxxi monxxi 148K avril 30 13:12 main.21804302ada5ff1c5275.css
-rw-r--r-- 1 monxxi monxxi  13K avril 30 13:12 vendors.21804302ada5ff1c5275.css
```

##### **Motivation for or Use Case**
In this VueJs blueprint, I would like change their locations to  target/classes/static/content

The goal of theses changes its to permit them to benefit of http cache thanks to cache header Cache-Control (see the PR of jhipster/generator-jhipster#11575) 

##### **Reproduce the error**
1 - generate the project with the yo-rc.json
2 - prepare the mysql database
3 - build and run it with prod profile.
./mvnw -Pprod 

##### **Related issues**
it may be  related to this issue on Angular client : jhipster/generator-jhipster#9289

##### **Suggest a Fix**
In the same way, Could we modify the webpack.prod.js to move these files to the directory content?

```
    new MiniCssExtractPlugin({
            // Options similar to the same options in webpackOptions.output
            // both options are optional
            filename: '[name].[contenthash].css',
            chunkFilename: '[id].css'
            filename: 'content/[name].[contenthash].css',
            chunkFilename: 'content/[id].css'
        }),
```

##### **JHipster Version(s)**
```
test-3@0.0.0 /home/monxxi/app/test3
└─┬ generator-jhipster-vuejs@1.7.0
  └── generator-jhipster@6.8.0 

```

##### **JHipster configuration**
<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "test.withvue",
      "nativeLanguage": "fr"
    },
    "jhipsterVersion": "6.8.0",
    "applicationType": "monolith",
    "baseName": "test3",
    "packageName": "test.withvue",
    "packageFolder": "test/withvue",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "vue",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1588198380918,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [
      {
        "name": "generator-jhipster-vuejs",
        "version": "1.7.0"
      }
    ],
    "enableTranslation": true,
    "nativeLanguage": "fr",
    "languages": ["fr", "en"],
    "blueprints": [
      {
        "name": "generator-jhipster-vuejs",
        "version": "1.7.0"
      }
    ]
  }
}

</pre>
</details>

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Browsers and Operating System**

openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Debian-3deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Debian-3deb10u1, mixed mode, sharing)

git version 2.20.1

node: v12.16.1

npm: 6.13.4

yeoman: 3.1.1

Docker version 19.03.8, build afacb8b7f0

docker-compose version 1.21.0, build unknown

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
can you take care of this ticket too @monxxi plz ?

**Comment by monxxi** [comment]
yes i can

**Comment by pascalgrimaud** [comment]
Closed by https://github.com/jhipster/jhipster-vuejs/pull/603
