### ISSUE TITLE
Cleanup and align with decided architecture

### ISSUE THREAD

**Issue by deepu105** [jhipster/jhipster-vuejs#6]
Make sure the following are followed, update and align where necessary

- [x] VueJS completely in Typescript
- ~~Tsx for templates~~
- [x] Bootstrap vue
- [x] Vuex for state management
- [x] Vue Router
- [x] Vue CLI as much as possible
- [x] Axios for HTTP
- [x] Vuei18n if it can be used without rewritting current i18n files, else use a transformation step or write our own i18n adapter like in React
- [x] Sass only
- [x] Jest for unit tests
- [x] Protractor if it works without any additional work else we can switch to Cypress
- [x] Tslint , prettier

**Comment by pascalgrimaud** [comment]
@sahbi-ktifa @atomfrede : do you think all these items need to be done before a 1st release ?

**Comment by sahbi-ktifa** [comment]
Yes I do, except for tsx template, I'd prefer to stick to current templates.

**Comment by atomfrede** [comment]
I would also keep the current templates. We definitely need some prettier config for Vue files.

**Comment by pascalgrimaud** [comment]
agree about tsx template, I'd prefer to stick to current templates

**Comment by sahbi-ktifa** [comment]
Ok, I removed this from our list.

**Comment by sahbi-ktifa** [comment]
With @pascalgrimaud, we noticed strange behavior with the .editorconfig file brought by the main generator. I'm gonna look into it (alongside prettier full compatibility) before closing this issue.

**Comment by sahbi-ktifa** [comment]
Wait for #197 before closing this one.

**Comment by sahbi-ktifa** [comment]
Closed due to #197

**Comment by sahbi-ktifa** [comment]
@jhipster/vuejs-developers how do we handle the bounty ? I've done several tasks on this one, is there anyone else involved ?

**Comment by atomfrede** [comment]
As you have done nearly all the work (and took the lead) here I think, there is no question you should claim the bounty :+1:

**Comment by pascalgrimaud** [comment]
Agree with @atomfrede 
You took the lead in this blueprint so it's well deserved

**Comment by sahbi-ktifa** [comment]
Bounty claimed https://opencollective.com/generator-jhipster/expenses/6439
