### ISSUE TITLE
CSS style : dev vs prod

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-vuejs#610]
The CSS style is completely different when using in dev and in prod profile.
It seems because the custom css is not used at all in prod and the boostrap one override our custom style.

**Comment by pascalgrimaud** [comment]
I think I'm not clear enough. I'll provider later more information to reproduce here

**Comment by atomfrede** [comment]
You mean the white and grey parts or something more severe?

PROD:
![image](https://user-images.githubusercontent.com/203401/81739083-0270a580-949b-11ea-8ac8-896aa4340018.png)

DEV:
![image](https://user-images.githubusercontent.com/203401/81739100-0c92a400-949b-11ea-926c-23141b3113a3.png)

**Comment by pascalgrimaud** [comment]
yes very minor here but there is a PR in jhipster control center, which uses Vue.js and the custom css is not used in prod.

And I saw the same for my gateway with vue.js for my current customer, with bootswatch

**Comment by atomfrede** [comment]
So dev is correct, right?

**Comment by pascalgrimaud** [comment]
I'll provide a screennshot as soon as possible :)
I don't know which one is the correct one. I think it's dev, yes

**Comment by atomfrede** [comment]
At least I think it looks "better" :)

**Comment by pascalgrimaud** [comment]
![dev](https://user-images.githubusercontent.com/9156882/81743480-005e1500-94a2-11ea-8f20-27399a722b34.png)

![prod](https://user-images.githubusercontent.com/9156882/81743526-166bd580-94a2-11ea-84f0-3f9054053566.png)

**Comment by pascalgrimaud** [comment]
Using this diff, solves the problem:

```diff
diff --git a/src/main/webapp/content/scss/vendor.scss b/src/main/webapp/content/scss/vendor.scss
index 560f820..df40ab7 100644
--- a/src/main/webapp/content/scss/vendor.scss
+++ b/src/main/webapp/content/scss/vendor.scss
@@ -10,5 +10,6 @@ eg $input-color: red;
 @import '~bootstrap/scss/bootstrap';
 @import '~bootstrap-vue/src/index.scss';
 @import '~bootswatch/dist/spacelab/bootswatch';
+@import 'global.scss';

```

@atomfrede : do you think it's the correct fix ?

**Comment by atomfrede** [comment]
I looks strange imho. Don't we have a vendor and app.css file in the end?

**Comment by pascalgrimaud** [comment]
yes probably, but to be honest, I sux in CSS... I couldn't help much here lol

**Comment by atomfrede** [comment]
Try to set the chunkSortMode to manual also in webpack.prod. 

`chunksSortMode: 'manual',`

**Comment by pascalgrimaud** [comment]
I think it works @atomfrede ! Thanks a lot

Our JHipster Control Center doesn't contain all new updates from Vue.js blueprint
See https://github.com/jhipster/jhipster-control-center/blob/master/webpack/webpack.prod.js#L71-L81

**Comment by pascalgrimaud** [comment]
With your suggestion, our sidebar menu in JHipster Control Center works well -> https://github.com/jhipster/jhipster-control-center/pull/56

![jhcc](https://user-images.githubusercontent.com/9156882/81747546-9006c200-94a8-11ea-9b1f-0ae677a4c6e7.png)

**Comment by atomfrede** [comment]
Seen the screenshot in the other pr. Looks really cool. Looking forward to the final result. I can provide a pr for the blueprint with the fix.
