### ISSUE TITLE
Swagger not available

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-vuejs#618]
Just encountered it with last version of Vue.js 1.8.0
If someone can confirm ?

I'll provide information later if needed

**Comment by pascalgrimaud** [comment]
The solution was found by @adilabed here:
https://github.com/jhipster/jhipster-control-center/pull/64/commits/f3d096360ed954fce8726e73c044c17a1bf20668

Would you like to contribute and provide the fix here too plz ?

cc @atomfrede as it's related to the recent upgrade of webpack

**Comment by adilabed** [comment]
My solution is not the most elegant one. The plugin CopyWebPackPlugin doesn't exclude ./node_modules/swagger-ui-dist/index.html' when copying the files from the selection.

**Comment by atomfrede** [comment]
Thats strange, the globoptions are supposed to exclude the index.html, basically migrated the settings to the new structure.

**Comment by pascalgrimaud** [comment]
Since this upgrade of webpack, the build is longer than before.
Did you see the same, @atomfrede ?

**Comment by atomfrede** [comment]
At least locally  I didn't notice, but also didn't compare.

Regarding ignore pattern, I found https://github.com/webpack-contrib/copy-webpack-plugin/issues/493

**Comment by atomfrede** [comment]
So maybe try `globOptions: { ignore: ['**/index.html'] },` instead.

**Comment by adilabed** [comment]
Ok perfect, It works!!

**Comment by atomfrede** [comment]
Awesome, do you provide a PR here?

**Comment by adilabed** [comment]
Will do now.

**Comment by atomfrede** [comment]
@pascalgrimaud Regarding the build performance, looking at https://webpack.js.org/guides/build-performance/#specific-tooling-issues, we don't follow their recommendations for typescript. Will give it a try this week.

**Comment by pascalgrimaud** [comment]
@atomfrede : do you think we should do a release with this fix ? I think it's important. And as Vue.js is still in blueprint, it's really easy to release

**Comment by atomfrede** [comment]
Yes let's do it.
