### ISSUE TITLE
Setting page title shows no I18n information.

### ISSUE THREAD

**Issue by china-fengguan** [jhipster/jhipster-vuejs#642]
Jason file isn't translated on user setting page in the latest version.

jhipster-vuejs/generators/client/templates/vue/src/main/webapp/app/account/settings/settings.vue.ejs

`<span v-bind:value="$t('settings.title')">User settings for [<b>{{username}}</b>]</span>`
should be changed to:
`<span v-html="$t('settings.title')">User settings for [<b>{{username}}</b>]</span>`

the fix works for me.
FYI.

**Comment by pascalgrimaud** [comment]
Thanks for reporting this @china-fengguan 
FYI, Vue.js has been integrated to main generator-jhipster

So I apply your fix there: https://github.com/jhipster/generator-jhipster/pull/12141
