### ISSUE TITLE
translations for falsy values : empty, 0 and false

### ISSUE THREAD

**Issue by SoniaLahi** [jhipster/jhipster-vuejs#644]
##### **Overview of the feature request**

In order to have a similar behaviour between frontend frameworks (cf. PR on [react falsy translations](https://github.com/jhipster/react-jhipster/pull/48)), when translation key values are 0 or false, it should return the value (0, false) instead of the key.

I will fix it this week.

##### **Motivation for or Use Case**

Standardization of translation behaviours in frontend apps.

##### **Related issues or PR**

Improvement requested here : https://github.com/jhipster/react-jhipster/pull/48#issuecomment-610908160

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by SoniaLahi** [comment]
Could you assign it to me ? Thank you

**Comment by pascalgrimaud** [comment]
@SoniaLahi : Vue has been merged into main generator-jhipster -> you should not work on this project, as it will be deprecated soon

**Comment by SoniaLahi** [comment]
thank you @pascalgrimaud ! I have duplicated the ticket on generator-jhipster https://github.com/jhipster/generator-jhipster/issues/12529 and we can close this one.
