### ISSUE TITLE
Does the project not support the creation of gateways? The gateway I created failed to log in and the page does not have a header

### ISSUE THREAD

**Issue by QAQtutu** [jhipster/jhipster-vuejs#651]
##### **Overview of the issue**

Unable to log in and the page does not have a header

##### **JHipster Version(s)**

generator-jhipster-vuejs  1.9.2
generator-jhipster 6.10.3

##### **Browsers and Operating System**

win10 chrome

**Comment by pascalgrimaud** [comment]
Hi @QAQtutu : which options did you choose, when creating your gateway ?

**Comment by QAQtutu** [comment]
Microservice gateway > N( Spring WebFlux) > JHipster Registry > JHipster UAA server > MySQL > No 
 cache > N(Hibernate 2nd level cache) > Maven

**Comment by QAQtutu** [comment]
I created a React version of the gateway and it works very well. But I only use Vue

**Comment by pascalgrimaud** [comment]
Ok, it's because UAA is not supported for Vue.js
See:
- https://github.com/jhipster/jhipster-vuejs/issues/529
- https://github.com/jhipster/jhipster-vuejs/issues/581
- https://github.com/jhipster/jhipster-vuejs/issues/643

Unless someone wants to code this part, it won't be done, so no support.
