### ISSUE TITLE
Migrate entity generator

### ISSUE THREAD

**Issue by deepu105** [jhipster/jhipster-vuejs#7]
Migrate entity generator templates to vueJS

**Comment by sahbi-ktifa** [comment]
@deepu105 I'd like to work on this one as I already have an early work on this matter

**Comment by clarenced** [comment]
Hi @deepu105 and @sahbi-ktifa , I would like to provide some help with this. I know VueJs and provided some help with jhipster-generator in the past. How can I start ?

**Comment by deepu105** [comment]
@sahbi-ktifa yes please. @clarenced please look at the open issues and pick one
