### ISSUE TITLE
Alert / Notification support 

### ISSUE THREAD

**Issue by sahbi-ktifa** [jhipster/jhipster-vuejs#72]
We should notify users when creating entities, etc...
We can do a jhi-alert-error like component which will display a notification upon creation, modification, ...

**Comment by pascalgrimaud** [comment]
Interesting ticket.
Do you want to help and contribute with us @richard-francois ?

**Comment by richard-francois** [comment]
Great ! i am in

**Comment by jdubois** [comment]
@sabrinapayet I just invited you to the "hipsters" team on the project, so I can affect the ticket to you. Plus, you can have the cool JHipster logo on your GitHub profile :-)

**Comment by pascalgrimaud** [comment]
@sabrinapayet : I assign to you the ticket. Thanks so much for helping the project!

**Comment by pascalgrimaud** [comment]
After some discussion with @sabrinapayet, I'm taking this ticket.
I'll do a PR soon

**Comment by pascalgrimaud** [comment]
Bug bounty claimed https://opencollective.com/generator-jhipster/expenses/6344
