### ISSUE TITLE
Consistency in EditorConfig/Prettier configurations

### ISSUE THREAD

**Issue by hdurix** [jhipster/jhipster-vuejs#73]
There is inconsistency in the tab style (2 or 4 spaces) between the generator code, the generated code and what it is defined in the `.editorconfig` of the generated app.

- Code is written with 4 spaces in the generator.
- Then prettier (I think) transforms the 4 spaces in 2 spaces
- Then .editorconfig force to use 4 spaces

We should use the same rules as react: 2 spaces everywhere (for `.ts`).

**Comment by pascalgrimaud** [comment]
I can take this ticket if you're ok @hdurix

**Comment by hdurix** [comment]
Great, go ahead then :) I'll keep my time for `vue-class-component`

**Comment by sahbi-ktifa** [comment]
I think to finish this issue, we should add .editorconfig file to the generated project :)

**Comment by deepu105** [comment]
yes indeed, aren't they already there from root generator?

Thanks & Regards,
Deepu

**Comment by sahbi-ktifa** [comment]
My bad, it is 😞

**Comment by sahbi-ktifa** [comment]
We should consider consistency between fields declaration order : 
- Public members / private injected fields 
- Decorators alignment (1 line or 2 lines)

**Comment by hdurix** [comment]
I think we should add tslint as it's done in Angular/react project.

They are configured to work accordingly to prettier rules.

**Comment by deepu105** [comment]
Didn't we add Tslint yet? its a must have to avoid spending time discussing
these stuff. I suggest we add the same tslint config as in React here as
well

Thanks & Regards,
Deepu

**Comment by sahbi-ktifa** [comment]
I'm gonna add specific editorconfig (like react) and prettier/lint config.
