### ISSUE TITLE
JHipster Pacman on load

### ISSUE THREAD

**Issue by sahbi-ktifa** [jhipster/jhipster-vuejs#75]
On latest main generator release, @sabrinapayet adds a wonderful Pacman animation during front loading. Even if Vue loads quickly, it would be cool to have the same behavior.

@sabrinapayet could you help on this one?

**Comment by pascalgrimaud** [comment]
Honestly, Vue loads so quickly !!!

It will be usefull only when the user starts the application in IntelliJ and forgets to build the front.

So yes, need to have this one.
