### ISSUE TITLE
Make use of bootstrap-vue

### ISSUE THREAD

**Issue by cmoine** [jhipster/jhipster-vuejs#8]
Any reason the project doesn't use https://bootstrap-vue.js.org ?

**Comment by sahbi-ktifa** [comment]
I'm sorry but I think it does, or did I wrongly used it?

Look at package.json and webapp/main.js in templates. Did I do something wrong?

**Comment by deepu105** [comment]
Yes it's indeed used

**Comment by cmoine** [comment]
Well I realized that afterwards: it is partialy using bootstrap-vue:
for instance https://github.com/jhipster/jhipster-vuejs/blob/master/generators/client/templates/webapp/app/components/account/LoginForm.vue

actually all files in https://github.com/jhipster/jhipster-vuejs/blob/master/generators/client/templates/webapp/app/components/account don't use any bootstrap vue for instance, with is not very consistent.
