### ISSUE TITLE
Refactoring: kebab case

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-vuejs#88]
The name of components, services etc are not consistent. 
I think we should stick to kebab case for all and start with lower case.

Are you ok @sahbi-ktifa @hdurix ?

**Comment by Gnuk** [comment]
I'm OK for components but I think Services can be changed in another story because we can use the Vue.js injection instead of a component mixin.

**Comment by sahbi-ktifa** [comment]
As service will be refactored using service injection, the renaming will be held there.
