### ISSUE TITLE
Replace moment?

### ISSUE THREAD

**Issue by atomfrede** [jhipster/jhipster-vuejs#94]
I know we want to be very consistent with angular and react but maybe we can try to replace the heavy moment bundle with date-fns maybe. What do you think?

**Comment by atomfrede** [comment]
I would say so. We use very limited functions from moment (a few weeks ago I tried day.js, nearly everything supported except parsing with format). day-fns does support all stuff we use and is much smaller and compatible with tree shaking. We could also think of changing the way we handle translations in the frontend. E.g. do a hard reload after chaining the language such that only the current locale is loaded for example or do some lazy loading stuff for i18n bundles.

See https://github.com/you-dont-need/You-Dont-Need-Momentjs for inspiration

**Comment by atomfrede** [comment]
@jhipster/vuejs-developers Should we give date-fns (2.x) a try? At least at the moment I only see moment used for parsing date/time strings.

**Comment by sahbi-ktifa** [comment]
Yes, we should at least try it! Go ahead if you can!

**Comment by atomfrede** [comment]
I will give it a try.

**Comment by atomfrede** [comment]
@jhipster/vuejs-developers I remember some discussion about how to handle instant and zoned date time inputs, but can't remember what we decided. Currently it is totally broken for me:

In FF the localDate field works quite well (same for chrome) you get a native browser control to select the date. For instant and zoned date time (which are both date-time inputs) I get nothing in firefox and a native control in chrome. When I save an entity now (in chrome) and I edit it again there is console error stating, that the input format is wrong and the input fields are not filled with the current data. 

In FF the string representation of the current data is shown in the input fields, which results in "invalid" data which can't be saved. How to handle that? All this is currently the case with moment, so not specific to day fns or so.

**Comment by atomfrede** [comment]
SO maybe I have found a solution, but doesn't look perfect to me.

```
<input id="datefnstest-zoneddatetimefield" 
                            type="datetime-local" 
                            class="form-control" name="zoneddatetimefield" 
                            :value="convertDateTimeFromServer($v.datefnstest.zoneddatetimefield.$model)"
                            @change="update2"
